LDMX Software: ldmxsw::Exception Class Reference
ldmxsw::Exception Class Reference
Standard base exception class with some useful output information.
#include <Exception.h>
Public Member Functions
Exception () throw ()
Exception (const std::string &name, const std::string &message, const std::string &module, int line, const std::string &function)
virtual ~Exception () throw ()
const std::string & name () const throw ()
const std::string & message () const throw ()
const std::string & module () const throw ()
const std::string & function () const throw ()
int line () const throw ()
virtual const char * what () const throw ()
Private Attributes
std::string name_
std::string message_
std::string module_
std::string function_
int line_ {0}
Detailed Description
Standard base exception class with some useful output information.
Note
It is strongly recommended to use the EXCEPTION_RAISE macro to throw exceptions.
Definition at line 21 of file Exception.h.
Constructor & Destructor Documentation
ldmxsw::Exception::Exception () throw () inline
Empty constructor.
Definition at line 27 of file Exception.h.
{
         }
ldmxsw::Exception::Exception (const std::string & name, const std::string & message, const std::string & module, int line, const std::string & function) inline
Class constructor.
Parameters
name Name of the exception.
message Extended message describing the exception.
module Filename in the source code where the exception occurred.
line Line in the source code where the exception occurred.
function Function in which the exception occurred.
Definition at line 38 of file Exception.h.
                                                                                                                                  :
                 name_ { name }, message_ { message }, module_ { module }, function_ { function }, line_ { line } {
         }
virtual ldmxsw::Exception::~Exception () throw () inline virtual
Class destructor.
Definition at line 45 of file Exception.h.
{
         }
Member Function Documentation
const std::string& ldmxsw::Exception::function () const throw () inline
Get the function name where the exception occurred.
Returns
The function name where the exception occurred.
Definition at line 76 of file Exception.h.
References function_.
Referenced by ldmxsw::Process::run().
{
             return function_;
         }
int ldmxsw::Exception::line () const throw () inline
Get the source line number where the exception occurred.
Returns
The source line number where the exception occurred.
Definition at line 84 of file Exception.h.
References line_.
Referenced by ldmxsw::Process::run().
{
             return line_;
         }
const std::string& ldmxsw::Exception::message () const throw () inline
Get the message of the exception.
Returns
The message of the exception.
Definition at line 60 of file Exception.h.
References message_.
Referenced by ldmxsw::Process::run().
{
             return message_;
         }
const std::string& ldmxsw::Exception::module () const throw () inline
Get the source filename where the exception occurred.
Returns
The source filename where the exception occurred.
Definition at line 68 of file Exception.h.
References module_.
Referenced by ldmxsw::Process::run().
{
             return module_;
         }
const std::string& ldmxsw::Exception::name () const throw () inline
Get the name of the exception.
Returns
The name of the exception.
Definition at line 52 of file Exception.h.
References name_.
Referenced by ldmxsw::Process::run().
{
             return name_;
         }
virtual const char* ldmxsw::Exception::what () const throw () inline virtual
The error message.
Returns
The error message.
Definition at line 92 of file Exception.h.
References message_.
{
             return message_.c_str();
         }
Member Data Documentation
std::string ldmxsw::Exception::function_ private
Function name where the exception occurred.
Definition at line 105 of file Exception.h.
Referenced by function().
int ldmxsw::Exception::line_ {0} private
Source line number where the exception occurred.
Definition at line 107 of file Exception.h.
Referenced by line().
std::string ldmxsw::Exception::message_ private
Error message.
Definition at line 101 of file Exception.h.
Referenced by message(), and what().
std::string ldmxsw::Exception::module_ private
Source filename where the exception occurred.
Definition at line 103 of file Exception.h.
Referenced by module().
std::string ldmxsw::Exception::name_ private
Exception name.
Definition at line 99 of file Exception.h.
Referenced by name().
The documentation for this class was generated from the following file:
Framework/include/Framework/Exception.h