LDMX Software: DummyProducer Class Reference
DummyProducer Class Reference
Defines a dummy Producer implementation that adds some random data to the event.
Public Member Functions
DummyProducer (const std::string &name, const ldmxsw::Process &process)
virtual void configure (const ldmxsw::ParameterSet &ps)
virtual void produce (event::Event &event)
virtual void onFileOpen ()
virtual void onFileClose ()
virtual void onProcessStart ()
virtual void onProcessEnd ()
Public Member Functions inherited from ldmxsw::Producer
Producer (const std::string &name, const Process &process)
Public Member Functions inherited from ldmxsw::EventProcessor
EventProcessor (const std::string &name, const Process &process)
virtual ~EventProcessor ()
virtual void onNewRun (int run)
virtual void onFileOpen (const std::string &filename)
virtual void onFileClose (const std::string &filename)
Private Attributes
TClonesArray * tca_ {nullptr}
int nParticles_ {0}
double aveEnergy_ {0}
std::vector< double > direction_
TRandom random_
Additional Inherited Members
Static Public Member Functions inherited from ldmxsw::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from ldmxsw::Producer
static const int CLASSTYPE {1}
Protected Attributes inherited from ldmxsw::EventProcessor
const Process & process_
Detailed Description
Defines a dummy Producer implementation that adds some random data to the event.
Definition at line 19 of file DummyProducer.cxx.
Member Function Documentation
virtual void DummyProducer::configure (const ldmxsw::ParameterSet & parameters) inline virtual
Callback for the EventProcessor to configure itself from the given set of parameters.
Parameters
parameters ParameterSet for configuration.
Reimplemented from ldmxsw::EventProcessor.
Definition at line 27 of file DummyProducer.cxx.
References ldmxsw::ParameterSet::getDouble(), ldmxsw::ParameterSet::getInteger(), and ldmxsw::ParameterSet::getVDouble().
{
             nParticles_ = ps.getInteger("nParticles_");
             aveEnergy_ = ps.getDouble("aveEnergy_");
             direction_ = ps.getVDouble("direction_");
         }
virtual void DummyProducer::onProcessEnd () inline virtual
Callback for the EventProcessor to take any necessary action when the processing of events finishes, such as calculating job-summary quantities.
Reimplemented from ldmxsw::EventProcessor.
Definition at line 60 of file DummyProducer.cxx.
{
             std::cout << "DummyProducer: Finishing processing!" << std::endl;
         }
virtual void DummyProducer::onProcessStart () inline virtual
Callback for the EventProcessor to take any necessary action when the processing of events starts, such as creating histograms.
Reimplemented from ldmxsw::EventProcessor.
Definition at line 55 of file DummyProducer.cxx.
{
             std::cout << "DummyProducer: Starting processing!" << std::endl;
             tca_ = new TClonesArray("event::SimParticle", 1000);
         }
virtual void DummyProducer::produce (event::Event & event) inline virtual
Process the event and put new data products into it.
Parameters
event The Event to process.
Implements ldmxsw::Producer.
Definition at line 33 of file DummyProducer.cxx.
References event::SimParticle::getEnergy(), event::SimParticle::setEnergy(), and event::SimParticle::setPdgID().
{
             std::cout << "DummyProducer: Analyzing an event!" << std::endl;
             int np = random_.Poisson(nParticles_);
             for (int i = 0; i < np; i++) {
                 event::SimParticle* a = (event::SimParticle*) tca_->ConstructedAt(i);
                 do {
                     a->setEnergy(random_.Gaus(aveEnergy_, 1.0));
                 } while (a->getEnergy() < 0);
                 a->setPdgID(i + 1);
             }
             event.add("simParticles", tca_);
         }
The documentation for this class was generated from the following file:
Framework/src/DummyProducer.cxx