LDMX Software: sim::UserEventAction Class Reference
sim::UserEventAction Class Reference
Implementation of user event action hook.
#include <UserEventAction.h>
Public Member Functions
UserEventAction ()
virtual ~UserEventAction ()
void BeginOfEventAction (const G4Event *anEvent)
void EndOfEventAction (const G4Event *anEvent)
Public Member Functions inherited from sim::PluginManagerAccessor
void setPluginManager (PluginManager *pluginManager)
PluginManager * getPluginManager ()
Additional Inherited Members
Protected Attributes inherited from sim::PluginManagerAccessor
PluginManager * pluginManager_
Detailed Description
Implementation of user event action hook.
Definition at line 24 of file UserEventAction.h.
Constructor & Destructor Documentation
sim::UserEventAction::UserEventAction () inline
Class constructor.
Definition at line 33 of file UserEventAction.h.
 {;}
virtual sim::UserEventAction::~UserEventAction () inline virtual
Class destructor.
Definition at line 38 of file UserEventAction.h.
 {;}
Member Function Documentation
void sim::UserEventAction::BeginOfEventAction (const G4Event * anEvent)
Implementation of begin of event hook.
Parameters
anEvent The Geant4 event.
Definition at line 20 of file UserEventAction.cxx.
References sim::PluginManager::beginEvent(), sim::TrackMap::clear(), and sim::TrackMap::getInstance().
{
     // Clear the global track map.
     TrackMap::getInstance()->clear();
     // Install custom trajectory container for the event.
     G4EventManager::GetEventManager()->GetNonconstCurrentEvent()->SetTrajectoryContainer(new TrajectoryContainer);
     pluginManager_->beginEvent(anEvent);
 }
void sim::UserEventAction::EndOfEventAction (const G4Event * anEvent)
Implementation of end of event hook.
Parameters
anEvent The Geant4 event.
Definition at line 31 of file UserEventAction.cxx.
References sim::PluginManager::endEvent().
{
     pluginManager_->endEvent(anEvent);
 }
The documentation for this class was generated from the following files:
SimApplication/include/SimApplication/UserEventAction.h
SimApplication/src/UserEventAction.cxx