LDMX Software: event::RunHeader Class Reference
event::RunHeader Class Reference
Run header providing information about a set of events.
#include <RunHeader.h>
Public Member Functions
RunHeader (int runNumber, std::string detectorName, int detectorVersion, std::string description)
RunHeader ()
virtual ~RunHeader ()
int getRunNumber () const
const std::string & getDetectorName () const
int getDetectorVersion () const
const std::string & getDescription () const
int getIntParameter (const std::string &name)
void setIntParameter (const std::string &name, int value)
float getFloatParameter (const std::string &name)
void setFloatParameter (const std::string &name, float value)
std::string getStringParameter (const std::string &name)
void setStringParameter (const std::string &name, std::string value)
Private Member Functions
ClassDef (RunHeader, 1)
Private Attributes
int runNumber_ {0}
std::string detectorName_ {""}
int detectorVersion_ {0}
std::string description_ {""}
std::map< std::string, int > intParameters_
std::map< std::string, float > floatParameters_
std::map< std::string,
std::string > stringParameters_
Detailed Description
Run header providing information about a set of events.
Note
This is a run header that can be used for describing sim or data events. It provides the run number, name of the detector model used when events were created, version of the detector used, and the type of the event branch. The header can also store named float, int or string parameters.
Definition at line 29 of file RunHeader.h.
Constructor & Destructor Documentation
event::RunHeader::RunHeader (int runNumber, std::string detectorName, int detectorVersion, std::string description) inline
Fully qualified class constructor (except for parameter values).
Parameters
runNumber The run number.
detectorName The name of the detector.
detectorVersion The version of the detector.
description A short description of the run.
Definition at line 40 of file RunHeader.h.
             : runNumber_(runNumber),
               detectorName_(detectorName),
               detectorVersion_(detectorVersion),
               description_(description) {
         }
event::RunHeader::RunHeader () inline
No argument class constructor.
Note
This exists for filling the object from a ROOT branch.
Definition at line 53 of file RunHeader.h.
 {;}
virtual event::RunHeader::~RunHeader () inline virtual
Class destructor.
Definition at line 58 of file RunHeader.h.
 {;}
Member Function Documentation
const std::string& event::RunHeader::getDescription () const inline
Get a short description of the run.
Returns
A short description of the run.
Definition at line 88 of file RunHeader.h.
References description_.
Referenced by sim::RootPersistencyManager::createRunHeader().
{
             return description_;
         }
const std::string& event::RunHeader::getDetectorName () const inline
Get the name of the detector used to create the events.
Returns
The name of the detector used to create the events.
Definition at line 72 of file RunHeader.h.
References detectorName_.
Referenced by sim::RootPersistencyManager::createRunHeader().
{
             return detectorName_;
         }
int event::RunHeader::getDetectorVersion () const inline
Get the version of the detector used to create the events.
Returns
The version of the detector used to create the events.
Definition at line 80 of file RunHeader.h.
References detectorVersion_.
Referenced by sim::RootPersistencyManager::createRunHeader().
{
             return detectorVersion_;
         }
float event::RunHeader::getFloatParameter (const std::string & name) inline
Get a float parameter value.
Parameters
name The name of the parameter.
Returns
value The parameter value.
Definition at line 116 of file RunHeader.h.
References floatParameters_.
{
             return floatParameters_[name];
         }
int event::RunHeader::getIntParameter (const std::string & name) inline
Get an int parameter value.
Parameters
name The name of the parameter.
Returns
The parameter value.
Definition at line 97 of file RunHeader.h.
References intParameters_.
{
             return intParameters_[name];
         }
int event::RunHeader::getRunNumber () const inline
Get the run number.
Returns
The run number.
Definition at line 64 of file RunHeader.h.
References runNumber_.
Referenced by sim::RootPersistencyManager::createRunHeader().
{
             return runNumber_;
         }
std::string event::RunHeader::getStringParameter (const std::string & name) inline
Get a string parameter value.
Parameters
name The name of the parameter.
Returns
value The parameter value.
Definition at line 134 of file RunHeader.h.
References stringParameters_.
{
             return stringParameters_[name];
         }
void event::RunHeader::setFloatParameter (const std::string & name, float value) inline
Set a float parameter value.
Parameters
name The name of the parameter.
Returns
value The parameter value.
Definition at line 125 of file RunHeader.h.
References floatParameters_.
{
             floatParameters_[name] = value;
         }
void event::RunHeader::setIntParameter (const std::string & name, int value) inline
Set an int parameter value.
Parameters
name The name of the parameter.
value The value of the parameter.
Returns
The parameter value.
Definition at line 107 of file RunHeader.h.
References intParameters_.
Referenced by sim::RootPersistencyManager::createRunHeader().
{
             intParameters_[name] = value;
         }
void event::RunHeader::setStringParameter (const std::string & name, std::string value) inline
Set a string parameter value.
Parameters
name The name of the parameter.
Returns
value The parameter value.
Definition at line 143 of file RunHeader.h.
References stringParameters_.
{
             stringParameters_[name] = value;
         }
Member Data Documentation
std::string event::RunHeader::description_ {""} private
The run description.
Definition at line 167 of file RunHeader.h.
Referenced by getDescription().
std::string event::RunHeader::detectorName_ {""} private
The detector name.
Definition at line 157 of file RunHeader.h.
Referenced by getDetectorName().
int event::RunHeader::detectorVersion_ {0} private
The detector version.
Definition at line 162 of file RunHeader.h.
Referenced by getDetectorVersion().
std::map<std::string, float> event::RunHeader::floatParameters_ private
The float parameters.
Definition at line 177 of file RunHeader.h.
Referenced by getFloatParameter(), and setFloatParameter().
std::map<std::string, int> event::RunHeader::intParameters_ private
The int parameters.
Definition at line 172 of file RunHeader.h.
Referenced by getIntParameter(), and setIntParameter().
int event::RunHeader::runNumber_ {0} private
The run number.
Definition at line 152 of file RunHeader.h.
Referenced by getRunNumber().
std::map<std::string, std::string> event::RunHeader::stringParameters_ private
The string parameters.
Definition at line 182 of file RunHeader.h.
Referenced by getStringParameter(), and setStringParameter().
The documentation for this class was generated from the following file:
Event/include/Event/RunHeader.h