LDMX Software: ldmxsw::Process Class Reference
ldmxsw::Process Class Reference
Class which represents the process under execution.
#include <Process.h>
Public Member Functions
Process (const std::string &passname)
const std::string & getPassName () const
void addToSequence (EventProcessor *evtproc)
void addFileToProcess (const std::string &filename)
void addDropKeepRule (const std::string &rule)
void setOutputFileName (const std::string &filenameOut)
void addOutputFileName (const std::string &filenameOut)
void setRunNumber (int run)
void setEventLimit (int limit=-1)
void run ()
Private Attributes
std::string passname_
int eventLimit_ {-1}
std::vector< EventProcessor * > sequence_
std::vector< std::string > inputFiles_
std::vector< std::string > outputFiles_
std::vector< std::string > dropKeepRules_
int runForGeneration_ {1}
Detailed Description
Class which represents the process under execution.
Definition at line 23 of file Process.h.
Constructor & Destructor Documentation
ldmxsw::Process::Process (const std::string & passname)
Class constructor.
Parameters
passname Processing pass label
Definition at line 9 of file Process.cxx.
                                           :
         passname_ { passname } {
 }
Member Function Documentation
void ldmxsw::Process::addDropKeepRule (const std::string & rule)
Add a rule for keeping/dropping event products
Note
Rules have the format: "keep/drop [name]_[pass]" Either or both of [name] and [pass] can be wildcards '*'. To keep all branches, use "keep *". Rules are processed in order and can overrule each other. Therefore, to keep only the simTracks from the "sim" pass of processing : "drop *_sim" then "keep simTracks_sim".
Parameters
rule
Definition at line 146 of file Process.cxx.
References dropKeepRules_.
Referenced by ldmxsw::ConfigurePython::makeProcess().
{
     dropKeepRules_.push_back(rule);
 }
void ldmxsw::Process::addFileToProcess (const std::string & filename)
Add an input file name to the list.
Parameters
filename Input ROOT event file name
Definition at line 143 of file Process.cxx.
References inputFiles_.
Referenced by ldmxsw::ConfigurePython::makeProcess().
{
     inputFiles_.push_back(filename);
 }
void ldmxsw::Process::addOutputFileName (const std::string & filenameOut)
Add an output file name to the list. There should either be the same number of output file names as input file names or just one output file name.
Parameters
filenameOut Output ROOT event file name
Definition at line 153 of file Process.cxx.
References outputFiles_.
Referenced by ldmxsw::ConfigurePython::makeProcess().
{
     outputFiles_.push_back(filenameOut);
 }
void ldmxsw::Process::addToSequence (EventProcessor * evtproc)
Add an event processor to the linear sequence of processors to run in this job
Parameters
evtproc EventProcessor (Producer, Analyzer) to add to the sequence
Definition at line 140 of file Process.cxx.
References sequence_.
Referenced by ldmxsw::ConfigurePython::makeProcess().
{
     sequence_.push_back(mod);
 }
const std::string& ldmxsw::Process::getPassName () const inline
Get the processing pass label.
Returns
The processing pass label.
Definition at line 37 of file Process.h.
References passname_.
{
             return passname_;
         }
void ldmxsw::Process::run ()
Run the process.
Definition at line 13 of file Process.cxx.
References ldmxsw::EventFile::addDrop(), ldmxsw::EventImpl::Clear(), ldmxsw::EventFile::close(), dropKeepRules_, eventLimit_, EXCEPTION_RAISE, ldmxsw::Exception::function(), ldmxsw::EventImpl::getEventHeader(), ldmxsw::EventImpl::getEventHeaderMutable(), event::EventHeader::getEventNumber(), event::EventHeader::getRun(), inputFiles_, ldmxsw::Exception::line(), ldmxsw::Exception::message(), ldmxsw::Exception::module(), ldmxsw::Exception::name(), ldmxsw::EventFile::nextEvent(), outputFiles_, passname_, event::EventHeader::Print(), runForGeneration_, sequence_, event::EventHeader::setEventNumber(), event::EventHeader::setRun(), event::EventHeader::setTimestamp(), and ldmxsw::EventFile::setupEvent().
Referenced by setRunNumber().
                   {
     try {
         int n_events_processed = 0;
         // first, notify everyone that we are starting
         for (auto module : sequence_) {
             module->onProcessStart();
         }
         // if we have no input files, but do have an event number, run for that number of events on an output file
         if (inputFiles_.empty() && eventLimit_ > 0) {
             EventFile outFile(outputFiles_[0], true);
             for (auto module : sequence_) {
                 module->onFileOpen(outputFiles_[0]);
             }
             EventImpl theEvent(passname_);
             outFile.setupEvent(&theEvent);
             while (n_events_processed < eventLimit_) {
                 event::EventHeader& eh = theEvent.getEventHeaderMutable();
                 eh.setRun(runForGeneration_);
                 eh.setEventNumber(n_events_processed + 1);
                 eh.setTimestamp(TTimeStamp());
                 theEvent.getEventHeader()->Print();
                 for (auto module : sequence_) {
                     if (dynamic_cast<Producer*>(module)) {
                         (dynamic_cast<Producer*>(module))->produce(theEvent);
                     } else if (dynamic_cast<Analyzer*>(module)) {
                         (dynamic_cast<Analyzer*>(module))->analyze(theEvent);
                     }
                 }
                 outFile.nextEvent();
                 theEvent.Clear();
                 n_events_processed++;
             }
             for (auto module : sequence_) {
                 module->onFileClose(outputFiles_[0]);
             }
             outFile.close();
         } else {
             if (!outputFiles_.empty() && outputFiles_.size() != inputFiles_.size()) {
                 EXCEPTION_RAISE("Process", "Unable to handle case of different number of input and output files (other than zero output files)");
             }
             // next, loop through the files
             int ifile = 0;
             int wasRun = -1;
             for (auto infilename : inputFiles_) {
                 EventFile inFile(infilename);
                 std::cout << "Process: Opening file " << infilename << std::endl;
                 EventFile* outFile(0);
                 if (!outputFiles_.empty()) {
                     outFile = new EventFile(outputFiles_[ifile], &inFile);
                     ifile++;
                     for (auto rule : dropKeepRules_) {
                         outFile->addDrop(rule);
                     }
                 }
                 for (auto module : sequence_) {
                     module->onFileOpen(infilename);
                 }
                 EventImpl theEvent(passname_);
                 if (outFile) {
                     outFile->setupEvent(&theEvent);
                 } else {
                     inFile.setupEvent(&theEvent);
                 }
                 EventFile* masterFile = (outFile) ? (outFile) : (&inFile);
                 while (masterFile->nextEvent() && (eventLimit_ < 0 || (n_events_processed) < eventLimit_)) {
                     // notify for new run if necessary
                     if (theEvent.getEventHeader()->getRun() != wasRun) {
                         wasRun = theEvent.getEventHeader()->getRun();
                         for (auto module : sequence_) {
                             module->onNewRun(wasRun);
                         }
                     }
                     TTimeStamp t;
                     std::cout << "[ Process ] :  Processing " << n_events_processed + 1 << " Run " << theEvent.getEventHeader()->getRun() << " Event " << theEvent.getEventHeader()->getEventNumber() << "  (" << t.AsString("lc") << ")" << std::endl;
                     for (auto module : sequence_) {
                         if (dynamic_cast<Producer*>(module)) {
                             (dynamic_cast<Producer*>(module))->produce(theEvent);
                         } else if (dynamic_cast<Analyzer*>(module)) {
                             (dynamic_cast<Analyzer*>(module))->analyze(theEvent);
                         }
                     }
                     n_events_processed++;
                 }
                 if (eventLimit_ > 0 && n_events_processed == eventLimit_) {
                     std::cout << "[ Process ] : Reached event limit of " << eventLimit_ << " events\n";
                 }
                 if (outFile) {
                     outFile->close();
                 }
                 inFile.close();
                 std::cout << "Process: Closing file " << infilename << std::endl;
                 for (auto module : sequence_) {
                     module->onFileClose(infilename);
                 }
             }
         }
         // finally, notify everyone that we are stopping
         for (auto module : sequence_) {
             module->onProcessEnd();
         }
     } catch (Exception& e) {
         std::cerr << "Framework Error [" << e.name() << "] : " << e.message() << std::endl;
         std::cerr << "  at " << e.module() << ":" << e.line() << " in " << e.function() << std::endl;
     }
 }
void ldmxsw::Process::setEventLimit (int limit = -1) inline
Set the maximum number of events to process. Processing will stop when either there are no more input events or when this number of events have been processed.
Parameters
limit Maximum number of events to process. -1 indicates no limit.
Definition at line 91 of file Process.h.
References eventLimit_.
Referenced by ldmxsw::ConfigurePython::makeProcess().
{
             eventLimit_ = limit;
         }
void ldmxsw::Process::setOutputFileName (const std::string & filenameOut)
Set a single output event file name
Parameters
filenameOut Output ROOT event file name
Definition at line 149 of file Process.cxx.
References outputFiles_.
{
     outputFiles_.clear();
     outputFiles_.push_back(filenameOut);
 }
void ldmxsw::Process::setRunNumber (int run) inline
Set the run number to be used when initiating new events from the job
Parameters
run Run number to use
Definition at line 83 of file Process.h.
References run(), and runForGeneration_.
Referenced by ldmxsw::ConfigurePython::makeProcess().
{
             runForGeneration_ = run;
         }
Member Data Documentation
std::vector<std::string> ldmxsw::Process::dropKeepRules_ private
Set of drop/keep rules.
Definition at line 113 of file Process.h.
Referenced by addDropKeepRule(), and run().
int ldmxsw::Process::eventLimit_ {-1} private
Limit on events to process.
Definition at line 105 of file Process.h.
Referenced by run(), and setEventLimit().
std::vector<std::string> ldmxsw::Process::inputFiles_ private
List of input files to process. May be empty if this Process will generate new events.
Definition at line 109 of file Process.h.
Referenced by addFileToProcess(), and run().
std::vector<std::string> ldmxsw::Process::outputFiles_ private
List of output file names. If empty, no output file will be created.
Definition at line 111 of file Process.h.
Referenced by addOutputFileName(), run(), and setOutputFileName().
std::string ldmxsw::Process::passname_ private
Processing pass name.
Definition at line 103 of file Process.h.
Referenced by getPassName(), and run().
int ldmxsw::Process::runForGeneration_ {1} private
Run number to use if generating events.
Definition at line 115 of file Process.h.
Referenced by run(), and setRunNumber().
std::vector<EventProcessor*> ldmxsw::Process::sequence_ private
Ordered list of EventProcessors to execute.
Definition at line 107 of file Process.h.
Referenced by addToSequence(), and run().
The documentation for this class was generated from the following files:
Framework/include/Framework/Process.h
Framework/src/Process.cxx