LDMX Software: EcalDigiProducer Class Reference
EcalDigiProducer Class Reference
Performs basic ECal digitization.
#include <EcalDigiProducer.h>
Public Types
typedef std::pair< int, int > layer_cell_pair
typedef std::pair< int, float > cell_energy_pair
Public Member Functions
EcalDigiProducer (const std::string &name, const ldmxsw::Process &process)
virtual void configure (const ldmxsw::ParameterSet &)
virtual void produce (event::Event &event)
Public Member Functions inherited from ldmxsw::Producer
Producer (const std::string &name, const Process &process)
Public Member Functions inherited from ldmxsw::EventProcessor
EventProcessor (const std::string &name, const Process &process)
virtual ~EventProcessor ()
virtual void onNewRun (int run)
virtual void onFileOpen (const std::string &filename)
virtual void onFileClose (const std::string &filename)
virtual void onProcessStart ()
virtual void onProcessEnd ()
Private Member Functions
layer_cell_pair hitToPair (SimCalorimeterHit *hit)
Private Attributes
TRandom2 * noiseInjector_ {nullptr}
TClonesArray * ecalDigis_ {nullptr}
EcalDetectorID detID_
EcalHexReadout * hexReadout_ {nullptr}
float meanNoise_ {0}
float readoutThreshold_ {0}
Static Private Attributes
static const int NUM_ECAL_LAYERS = 33
static const int NUM_LAYERS_FOR_MED_CAL = 10
static const int BACK_ECAL_STARTING_LAYER = 20
Additional Inherited Members
Static Public Member Functions inherited from ldmxsw::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from ldmxsw::Producer
static const int CLASSTYPE {1}
Protected Attributes inherited from ldmxsw::EventProcessor
const Process & process_
Detailed Description
Performs basic ECal digitization.
Definition at line 32 of file EcalDigiProducer.h.
Member Function Documentation
void EcalDigiProducer::configure (const ldmxsw::ParameterSet & parameters) virtual
Callback for the EventProcessor to configure itself from the given set of parameters.
Parameters
parameters ParameterSet for configuration.
Reimplemented from ldmxsw::EventProcessor.
Definition at line 29 of file EcalDigiProducer.cxx.
References ldmxsw::ParameterSet::getDouble(), and ldmxsw::ParameterSet::getInteger().
{
     hexReadout_ = new EcalHexReadout();
     noiseInjector_ = new TRandom2(ps.getInteger("randomSeed", 0));
     meanNoise_ = ps.getDouble("meanNoise");
     readoutThreshold_ = ps.getDouble("readoutThreshold");
     ecalDigis_ = new TClonesArray("event::EcalHit", 10000);
 }
void EcalDigiProducer::produce (event::Event & event) virtual
Process the event and put new data products into it.
Parameters
event The Event to process.
Implements ldmxsw::Producer.
Definition at line 39 of file EcalDigiProducer.cxx.
References event::Event::getCollection(), event::SimCalorimeterHit::getEdep(), event::SimCalorimeterHit::getID(), event::SimCalorimeterHit::getTime(), event::CalorimeterHit::setAmplitude(), event::CalorimeterHit::setEnergy(), event::CalorimeterHit::setID(), and event::CalorimeterHit::setTime().
{
     TClonesArray* ecalSimHits = (TClonesArray*) event.getCollection(event::EventConstants::ECAL_SIM_HITS);
     int numEcalSimHits = ecalSimHits->GetEntries();
     std::cout << "[ EcalDigiProducer ] : Got " << numEcalSimHits << " ECal hits in event " << event.getEventHeader()->getEventNumber() << std::endl;
     //First we simulate noise injection into each hit and store layer-wise max cell ids
     int iHitOut = 0;
     for (int iHit = 0; iHit < numEcalSimHits; iHit++) {
         SimCalorimeterHit* EcalHit = (SimCalorimeterHit*) ecalSimHits->At(iHit);
         double hitNoise = noiseInjector_->Gaus(0, meanNoise_);
         layer_cell_pair hit_pair = hitToPair(EcalHit);
         event::EcalHit* hit = (event::EcalHit*) (ecalDigis_->ConstructedAt(iHit));
         //  hit->setLayer(hit_pair.first);
         hit->setID(EcalHit->getID());
         hit->setAmplitude(EcalHit->getEdep());
         double energy = EcalHit->getEdep() + hitNoise;
         if (energy > readoutThreshold_) {
             hit->setEnergy(energy);
             hit->setTime(EcalHit->getTime());
         } else {
             hit->setEnergy(0);
             hit->setTime(-1000);
         }
     }
     event.add("ecalDigis", ecalDigis_);
 }
The documentation for this class was generated from the following files:
EventProc/include/EventProc/EcalDigiProducer.h
EventProc/src/EcalDigiProducer.cxx