LDMX Software: sim::UserRunAction Class Reference
sim::UserRunAction Class Reference
Implementation of user run action hook.
#include <UserRunAction.h>
Public Member Functions
UserRunAction ()
virtual ~UserRunAction ()
void BeginOfRunAction (const G4Run *aRun)
void EndOfRunAction (const G4Run *aRun)
Public Member Functions inherited from sim::PluginManagerAccessor
void setPluginManager (PluginManager *pluginManager)
PluginManager * getPluginManager ()
Additional Inherited Members
Protected Attributes inherited from sim::PluginManagerAccessor
PluginManager * pluginManager_
Detailed Description
Implementation of user run action hook.
Definition at line 23 of file UserRunAction.h.
Constructor & Destructor Documentation
sim::UserRunAction::UserRunAction ()
Class constructor.
Definition at line 9 of file UserRunAction.cxx.
{
 }
sim::UserRunAction::~UserRunAction () virtual
Class destructor.
Definition at line 12 of file UserRunAction.cxx.
{
 }
Member Function Documentation
void sim::UserRunAction::BeginOfRunAction (const G4Run * aRun)
Implementation of begin run hook.
Parameters
aRun The current Geant4 run info.
Definition at line 15 of file UserRunAction.cxx.
References sim::PluginManager::beginRun(), sim::RootPersistencyManager::getInstance(), and sim::RootPersistencyManager::Initialize().
{
 // Open the ROOT writer.
 if (RootPersistencyManager::getInstance()) {
     RootPersistencyManager::getInstance()->Initialize();
 }
 pluginManager_->beginRun(aRun);
 }
void sim::UserRunAction::EndOfRunAction (const G4Run * aRun)
Implementation of end run hook.
Parameters
aRun The current Geant4 run info.
Definition at line 26 of file UserRunAction.cxx.
References sim::PluginManager::endRun().
{
 pluginManager_->endRun(aRun);
 }
The documentation for this class was generated from the following files:
SimApplication/include/SimApplication/UserRunAction.h
SimApplication/src/UserRunAction.cxx