LDMX Software: TriggerProcessor Class Reference
TriggerProcessor Class Reference
Provides a trigger decision for recon using a TriggerResult object.
#include <TriggerProcessor.h>
Public Member Functions
TriggerProcessor (const std::string &name, const ldmxsw::Process &process)
virtual void configure (const ldmxsw::ParameterSet &pSet)
virtual void produce (event::Event &event)
Public Member Functions inherited from ldmxsw::Producer
Producer (const std::string &name, const Process &process)
Public Member Functions inherited from ldmxsw::EventProcessor
EventProcessor (const std::string &name, const Process &process)
virtual ~EventProcessor ()
virtual void onNewRun (int run)
virtual void onFileOpen (const std::string &filename)
virtual void onFileClose (const std::string &filename)
virtual void onProcessStart ()
virtual void onProcessEnd ()
Private Attributes
float layerESumCut_ {0}
int mode_ {0}
int startLayer_ {0}
int endLayer_ {0}
TString algoName_
event::TriggerResult result_
Additional Inherited Members
Static Public Member Functions inherited from ldmxsw::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from ldmxsw::Producer
static const int CLASSTYPE {1}
Protected Attributes inherited from ldmxsw::EventProcessor
const Process & process_
Detailed Description
Provides a trigger decision for recon using a TriggerResult object.
Definition at line 19 of file TriggerProcessor.h.
Member Function Documentation
void TriggerProcessor::configure (const ldmxsw::ParameterSet & parameters) virtual
Callback for the EventProcessor to configure itself from the given set of parameters.
Parameters
parameters ParameterSet for configuration.
Reimplemented from ldmxsw::EventProcessor.
Definition at line 14 of file TriggerProcessor.cxx.
References ldmxsw::ParameterSet::getDouble(), and ldmxsw::ParameterSet::getInteger().
{
     layerESumCut_ = pSet.getDouble("threshold");
     mode_ = pSet.getInteger("mode");
     startLayer_ = pSet.getInteger("start_layer");
     endLayer_ = pSet.getInteger("end_layer");
     if (mode_ == 0) {
         algoName_ = "LayerSumTrig";
     } else if (mode_ == 1) {
         algoName_ = "CenterTower";
     }
 }
void TriggerProcessor::produce (event::Event & event) virtual
Process the event and put new data products into it.
Parameters
event The Event to process.
Grab the Ecal hit collection for the given event
Loop over all ecal hits in the given event
Implements ldmxsw::Producer.
Definition at line 28 of file TriggerProcessor.cxx.
References event::CalorimeterHit::getEnergy(), and event::CalorimeterHit::getLayer().
{
     using namespace event;
     const TClonesArray *ecalDigis = event.getCollection("ecalDigis");
     int numEcalHits = ecalDigis->GetEntriesFast();
     std::vector<double> layerDigiE(100, 0.0); // big empty vector..
     for (int iHit = 0; iHit < numEcalHits; ++iHit) {
         EcalHit *hit = (EcalHit*) ecalDigis->At(iHit);
         if (hit->getLayer() < layerDigiE.size()) { // just to be safe...
             if (mode_ == 0) { // Sum over all cells in a given layer
                 layerDigiE[hit->getLayer()] += hit->getEnergy();
             } else if (mode_ == 1) { // Sum over cells in central tower only
                 //std::pair<float, float> xyPos = hit->getCellCentroidXYPair(hit->getID());
                 //float cellRadius = sqrt(pow(xyPos.first, 2) + pow(xyPos.second, 2));
                 //if (cellRadius < MAGICNUMBERHERE) {
                 //    layerDigiE[hit->getLayer()] += hit->getEnergy();
                 //}
             }
         }
     }
     float layerSum = 0;
     bool pass = false;
     for (int iL = startLayer_; iL < endLayer_; ++iL) {
         layerSum += layerDigiE[iL];
     }
     pass = (layerSum <= layerESumCut_);
     result_.set(algoName_, pass, 3);
     result_.setAlgoVar(0, layerSum);
     result_.setAlgoVar(1, layerESumCut_);
     result_.setAlgoVar(2, endLayer_ - startLayer_);
     event.addToCollection("Trigger", result_);
 }
The documentation for this class was generated from the following files:
EventProc/include/EventProc/TriggerProcessor.h
EventProc/src/TriggerProcessor.cxx