LDMX Software: detdescr::EcalHexReadout Class Reference
detdescr::EcalHexReadout Class Reference
Implementation of ECal hexagonal cell readout.
#include <EcalHexReadout.h>
Public Member Functions
EcalHexReadout (const double width=1000, const double side=4.59360)
virtual ~EcalHexReadout ()
int getCellId (float x, float y)
std::pair< float, float > getCellCentroidXYPair (int cellID)
bool isInShowerInnerRing (int centroidId, int cellId)
bool isInShowerOuterRing (int centroidId, int cellId)
Private Types
typedef std::pair< float, float > XYCoords
Private Member Functions
std::vector< int > getInnerRingCellIds (int cellId)
std::vector< int > getOuterRingCellIds (int cellId)
void buildMap (Double_t xstart, Double_t ystart, Double_t a, Int_t k, Int_t s)
Private Attributes
TH2Poly * ecalMap
std::map< int, XYCoords > cellIdtoCoords
Detailed Description
Implementation of ECal hexagonal cell readout.
Note
This class implements a hexagonal cell readout across all modules in the ECal. It can provide a cell ID given a position and can also translate a cell ID back into a position of the cell centroid.
Definition at line 28 of file EcalHexReadout.h.
Constructor & Destructor Documentation
detdescr::EcalHexReadout::EcalHexReadout (const double width = 1000, const double side = 4.59360)
Class constructor.
Parameters
width The width of the grid [mm].
side The length of the hexagon's side [mm].
Definition at line 6 of file EcalHexReadout.cxx.
References buildMap().
{
     ecalMap = new TH2Poly();
     // Center a cell at (x,y)=(0,0) and ensure coverage up to/past width/2 in all 4 directions,
     // assuming each cell is lying on a side.
     unsigned ncellwide = width / (2. * side);
     unsigned ny = ncellwide + 1;
     unsigned nx = ncellwide + 4;
     double xstart = -((double) ncellwide + 0.5) * side;
     double ystart = -((double) ncellwide + 1) * side * sqrt(3) / 2;
     // std::cout << " -- Initialising HoneyComb with parameters: " << std::endl << " ---- (xstart,ystart) = (" << xstart << "," << ystart << ")" << ", side = " << side << ", nx = " << nx << ", ny=" << ny << std::endl;
     buildMap(xstart, ystart, side, ny, nx);
     TListIter next(ecalMap->GetBins());
     TObject *obj = 0;
     TH2PolyBin *polyBin = 0;
     while ((obj = next())) {
         polyBin = (TH2PolyBin*) obj;
         int id = polyBin->GetBinNumber();
         double x = (polyBin->GetXMax() + polyBin->GetXMin()) / 2.;
         double y = (polyBin->GetYMax() + polyBin->GetYMin()) / 2.;
         cellIdtoCoords.insert(std::pair<int,XYCoords>(id, std::make_pair(x, y)));
     }
 }
virtual detdescr::EcalHexReadout::~EcalHexReadout () inline virtual
Class destructor.
Definition at line 42 of file EcalHexReadout.h.
{
             delete ecalMap;
         }
Member Function Documentation
void detdescr::EcalHexReadout::buildMap (Double_t xstart, Double_t ystart, Double_t a, Int_t k, Int_t s) private
Todo:
Document this function.
Definition at line 34 of file EcalHexReadout.cxx.
Referenced by EcalHexReadout().
{
     // Add the bins
     Double_t numberOfHexagonsInAColumn;
     Double_t x[6], y[6];
     Double_t xloop, yloop, ytemp;
     Double_t sqrt_three = sqrt(3);
     xloop = xstart;
     yloop = ystart + a * sqrt_three / 2.0;
     for (int sCounter = 0; sCounter < s; sCounter++) {
         ytemp = yloop; // Resets the temp variable
         // Determine the number of hexagons in that column
         if (sCounter % 2 == 0) {
             numberOfHexagonsInAColumn = k;
         } else {
             numberOfHexagonsInAColumn = k - 1;
         }
         for (int kCounter = 0; kCounter < numberOfHexagonsInAColumn; kCounter++) {
             // Go around the hexagon
             x[0] = xloop;
             y[0] = ytemp;
             x[1] = x[0] + a / 2.0;
             y[1] = y[0] + a * sqrt_three / 2.0;
             x[2] = x[1] + a;
             y[2] = y[1];
             x[3] = x[2] + a / 2.0;
             y[3] = y[1] - a * sqrt_three / 2.0;
             x[4] = x[2];
             y[4] = y[3] - a * sqrt_three / 2.0;
             x[5] = x[1];
             y[5] = y[4];
             ecalMap->AddBin(6, x, y);
             // Go up
             ytemp += a * sqrt_three;
         }
         // Increment the starting position
         if (sCounter % 2 == 0)
             yloop += a * sqrt_three / 2.0;
         else
             yloop -= a * sqrt_three / 2.0;
         xloop += 1.5 * a;
     }
 }
std::pair<float, float> detdescr::EcalHexReadout::getCellCentroidXYPair (int cellID) inline
Get an XY position from a cell ID.
Parameters
cellID The cell ID.
Returns
The XY position of the cell.
Definition at line 60 of file EcalHexReadout.h.
Referenced by sim::EcalHitIO::writeHitsCollection().
{
             std::pair<std::map<int, XYCoords>::iterator, bool> isInserted;
             isInserted = cellIdtoCoords.insert(std::pair<int,XYCoords>(cellID,std::pair<float,float>(0, 0)));
             if (isInserted.second == true) {
                 throw std::runtime_error("Error: cell " + std::to_string(cellID) + " is not valid");
             }
             return isInserted.first->second;
         }
int detdescr::EcalHexReadout::getCellId (float x, float y) inline
Get a cell ID from an XY position.
Parameters
x The X position.
y The Y position.
Definition at line 51 of file EcalHexReadout.h.
Referenced by sim::EcalSD::ProcessHits().
{
             return ecalMap->FindBin(x, y);
         }
std::vector<int> detdescr::EcalHexReadout::getInnerRingCellIds (int cellId) inline private
Todo:
Document this function.
Definition at line 98 of file EcalHexReadout.h.
Referenced by isInShowerInnerRing().
{
             return {cellId - 1, cellId - 1 - 76, cellId - 1 + 77,
                 cellId + 1, cellId + 1 - 77, cellId + 1 + 76};
         }
std::vector<int> detdescr::EcalHexReadout::getOuterRingCellIds (int cellId) inline private
Todo:
Document this function.
Definition at line 106 of file EcalHexReadout.h.
Referenced by isInShowerOuterRing().
{
             return {cellId - 2 * 76, cellId - 2 * 76- 1, cellId - 2 * 76 - 2,
                 cellId + 2 * 78, cellId + 2 * 78 - 1, cellId + 2 * 78 - 2,
                 cellId + 2, cellId + 2 - 77, cellId + 2 + 76,
                 cellId - 2, cellId - 2 - 76, cellId - 2 + 77};
         }
bool detdescr::EcalHexReadout::isInShowerInnerRing (int centroidId, int cellId) inline
Todo:
Document this function.
Definition at line 72 of file EcalHexReadout.h.
References getInnerRingCellIds().
{
             bool matched = false;
             for (auto ringId : getInnerRingCellIds(centroidId)) {
                 if (cellId == ringId)
                     matched = true;
             }
             return matched;
         }
bool detdescr::EcalHexReadout::isInShowerOuterRing (int centroidId, int cellId) inline
Todo:
Document this function.
Definition at line 84 of file EcalHexReadout.h.
References getOuterRingCellIds().
{
             bool matched = false;
             for (auto ringId : getOuterRingCellIds(centroidId)) {
                 if (cellId == ringId)
                     matched = true;
             }
             return matched;
         }
The documentation for this class was generated from the following files:
DetDescr/include/DetDescr/EcalHexReadout.h
DetDescr/src/EcalHexReadout.cxx