LDMX Software: HcalDigiProducer Class Reference
HcalDigiProducer Class Reference
Performs digitization of simulated HCal data.
#include <HcalDigiProducer.h>
Public Types
typedef int layer
typedef std::pair< double, double > zboundaries
Public Member Functions
HcalDigiProducer (const std::string &name, const ldmxsw::Process &process)
virtual void configure (const ldmxsw::ParameterSet &)
virtual void produce (event::Event &event)
Public Member Functions inherited from ldmxsw::Producer
Producer (const std::string &name, const Process &process)
Public Member Functions inherited from ldmxsw::EventProcessor
EventProcessor (const std::string &name, const Process &process)
virtual ~EventProcessor ()
virtual void onNewRun (int run)
virtual void onFileOpen (const std::string &filename)
virtual void onFileClose (const std::string &filename)
virtual void onProcessStart ()
virtual void onProcessEnd ()
Private Attributes
TClonesArray * hits_ {nullptr}
TRandom * random_ {0}
std::map< layer, zboundaries > hcalLayers_
bool verbose_ {false}
detdescr::DetectorID * detID_ {nullptr}
float meanNoise_ {0}
int nProcessed_ {0}
Static Private Attributes
static const float FIRST_LAYER_ZPOS = 569.5
static const float LAYER_ZWIDTH = 60.
static const int NUM_HCAL_LAYERS = 15
static const float MEV_PER_MIP = 1.40
static const float PE_PER_MIP = 13.5 * 6. / 4.
Additional Inherited Members
Static Public Member Functions inherited from ldmxsw::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from ldmxsw::Producer
static const int CLASSTYPE {1}
Protected Attributes inherited from ldmxsw::EventProcessor
const Process & process_
Detailed Description
Performs digitization of simulated HCal data.
Definition at line 23 of file HcalDigiProducer.h.
Member Function Documentation
void HcalDigiProducer::configure (const ldmxsw::ParameterSet & parameters) virtual
Callback for the EventProcessor to configure itself from the given set of parameters.
Parameters
parameters ParameterSet for configuration.
Reimplemented from ldmxsw::EventProcessor.
Definition at line 33 of file HcalDigiProducer.cxx.
References ldmxsw::ParameterSet::getDouble(), and ldmxsw::ParameterSet::getInteger().
{
     detID_ = new DefaultDetectorID();
     random_ = new TRandom(ps.getInteger("randomSeed", 1000));
     meanNoise_ = ps.getDouble("meanNoise");
 }
void HcalDigiProducer::produce (event::Event & event) virtual
Process the event and put new data products into it.
Parameters
event The Event to process.
Implements ldmxsw::Producer.
Definition at line 39 of file HcalDigiProducer.cxx.
References event::Event::getCollection(), event::SimCalorimeterHit::getEdep(), detdescr::DetectorID::getFieldValue(), event::SimCalorimeterHit::getID(), event::SimCalorimeterHit::getPosition(), event::SimCalorimeterHit::getTime(), event::CalorimeterHit::setAmplitude(), event::CalorimeterHit::setEnergy(), event::CalorimeterHit::setID(), event::HcalHit::setPE(), detdescr::DetectorID::setRawValue(), event::CalorimeterHit::setTime(), and detdescr::DetectorID::unpack().
{
     std::map<int, int> hcalLayerNum, hcalLayerPEs, hcalDetId;
     std::map<int, float> hcalZpos;
     std::map<int, float> hcalLayerEdep, hcalLayerTime;
     // looper over sim hits and aggregate energy depositions for each detID
     TClonesArray* hcalHits = (TClonesArray*) event.getCollection(event::EventConstants::HCAL_SIM_HITS, "sim");
     int numHCalSimHits = hcalHits->GetEntries();
     for (int iHit = 0; iHit < numHCalSimHits; iHit++) {
         SimCalorimeterHit* simHit = (SimCalorimeterHit*) hcalHits->At(iHit);
         //int detID=simHit->getID();
         int detIDraw = simHit->getID();
         if (verbose_)
             std::cout << "detIDraw: " << detIDraw << std::endl;
         detID_->setRawValue(detIDraw);
         detID_->unpack();
         int layer = detID_->getFieldValue("layer");
         if (verbose_)
             std::cout << "layer: " << layer << std::endl;
         if (hcalLayerEdep.find(simHit->getID()) == hcalLayerEdep.end()) {
             // first hit, initialize
             hcalLayerEdep[detIDraw] = simHit->getEdep();
             hcalLayerTime[detIDraw] = simHit->getTime() * simHit->getEdep();
             hcalDetId[detIDraw] = detIDraw;
             hcalZpos[detIDraw] = simHit->getPosition()[2];
             hcalLayerNum[detIDraw] = layer;
         } else {
             // not first hit, aggregate
             hcalLayerEdep[detIDraw] += simHit->getEdep();
             hcalLayerTime[detIDraw] += simHit->getTime() * simHit->getEdep();
         }
     } // end loop over sim hits
     // loop over detID (layers) and simulate number of PEs
     int ihit = 0;
     for (std::map<int, float>::iterator it = hcalLayerEdep.begin(); it != hcalLayerEdep.end(); ++it) {
         int detIDraw = it->first;
         double depEnergy = hcalLayerEdep[detIDraw];
         hcalLayerTime[detIDraw] = hcalLayerTime[detIDraw] / hcalLayerEdep[detIDraw];
         double meanPE = depEnergy / MEV_PER_MIP * PE_PER_MIP;
         //        std::default_random_engine generator;
         //std::poisson_distribution<int> distribution(meanPE);
         hcalLayerPEs[detIDraw] = random_->Poisson(meanPE);
         hcalLayerPEs[detIDraw] += random_->Gaus(meanNoise_);
         if (verbose_) {
             std::cout << "detID: " << detIDraw << std::endl;
             std::cout << "Layer: " << hcalLayerNum[detIDraw] << std::endl;
             std::cout << "Edep: " << hcalLayerEdep[detIDraw] << std::endl;
             std::cout << "numPEs: " << hcalLayerPEs[detIDraw] << std::endl;
             std::cout << "time: " << hcalLayerTime[detIDraw] << std::endl;
             std::cout << "z: " << hcalZpos[detIDraw] << std::endl;
         }        // end verbose
         int layer = hcalLayerNum[detIDraw];
         double energy = hcalLayerPEs[detIDraw] / PE_PER_MIP * MEV_PER_MIP; // need to add in a weighting factor eventually
         event::HcalHit *hit = (event::HcalHit*) (hits_->ConstructedAt(ihit));
         //  hit->setLayer(layer);
         hit->setPE(hcalLayerPEs[detIDraw]);
         hit->setAmplitude(hcalLayerPEs[detIDraw]);
         hit->setEnergy(energy);
         hit->setTime(hcalLayerTime[detIDraw]);
         hit->setID(detIDraw);
         //  hit->setZpos(hcalZpos[detIDraw]);
         ihit++;
     } // end loop over detIDs (layers)
       // put it into the event
     event.add("hcalDigis", hits_);
 }
The documentation for this class was generated from the following files:
EventProc/include/EventProc/HcalDigiProducer.h
EventProc/src/HcalDigiProducer.cxx