LDMX Software: sim::EcalHitIO Class Reference
sim::EcalHitIO Class Reference
Provides hit readout for simulated ECal detector.
#include <EcalHitIO.h>
Public Types
typedef std::pair< int, int > LayerCellPair
Public Member Functions
EcalHitIO (SimParticleBuilder *simParticleBuilder)
~EcalHitIO ()
void writeHitsCollection (G4CalorimeterHitsCollection *hc, TClonesArray *outputColl)
void setEnableHitContribs (bool enableHitContribs)
void setCompressHitContribs (bool compressHitContribs)
Private Attributes
SimParticleBuilder * simParticleBuilder_
EcalHexReadout hexReadout_
EcalDetectorID detID_
bool enableHitContribs_ {true}
bool compressHitContribs_ {true}
Detailed Description
Provides hit readout for simulated ECal detector.
Note
This class uses the EcalHexReadout to transform the G4CalorimeterHit hits collection into a collection of SimCalorimeterHit objects assigned to hexagonal cells by their ID and positions. Energy depositions in the same cells are combined together into single hits.
It can be run in three modes:
Compressed hit contributions combined by matching SimParticle and PDG code (default mode)
Full hit contributions with one record per step (when compressHitContribs_ is false)
No hit contribution information where energy is combined but vectors are not filled (when enableHitContribs_ is false)
Definition at line 49 of file EcalHitIO.h.
Member Typedef Documentation
typedef std::pair<int, int> sim::EcalHitIO::LayerCellPair
Layer-cell pair.
Definition at line 56 of file EcalHitIO.h.
Constructor & Destructor Documentation
sim::EcalHitIO::EcalHitIO (SimParticleBuilder * simParticleBuilder)
Class constructor.
Parameters
simParticleBuilder Object for accessing SimParticle store for the event.
Definition at line 14 of file EcalHitIO.cxx.
     : simParticleBuilder_(simParticleBuilder) {
 }
sim::EcalHitIO::~EcalHitIO () inline
Class destructor.
Definition at line 69 of file EcalHitIO.h.
 {;}
Member Function Documentation
void sim::EcalHitIO::setCompressHitContribs (bool compressHitContribs) inline
Set whether hit contributions should be compressed by particle and PDG code.
Parameters
compressHitContribs True to compress hit contribution information.
Definition at line 90 of file EcalHitIO.h.
References compressHitContribs_.
Referenced by sim::RootPersistencyManager::setCompressHitContribs().
{
             compressHitContribs_ = compressHitContribs;
         }
void sim::EcalHitIO::setEnableHitContribs (bool enableHitContribs) inline
Set whether hit contributions should be enabled for the output hits.
Parameters
enableHitContribs True to enable hit contributions.
Definition at line 82 of file EcalHitIO.h.
References enableHitContribs_.
Referenced by sim::RootPersistencyManager::setEnableHitContribs().
{
             enableHitContribs_ = enableHitContribs;
         }
void sim::EcalHitIO::writeHitsCollection (G4CalorimeterHitsCollection * hc, TClonesArray * outputColl)
Write out a Geant4 hits collection to the provided ROOT array.
Parameters
hc The input hits collection.
outputColl The output collection in ROOT.
Assign XY position to the hit using the ECal hex readout. Z position is set from the original hit, which should be the middle of the sensor.
Definition at line 18 of file EcalHitIO.cxx.
References event::SimCalorimeterHit::addContrib(), compressHitContribs_, detID_, enableHitContribs_, event::SimCalorimeterHit::findContribIndex(), sim::SimParticleBuilder::findSimParticle(), detdescr::EcalHexReadout::getCellCentroidXYPair(), event::SimCalorimeterHit::getEdep(), sim::G4CalorimeterHit::getEdep(), detdescr::DetectorID::getFieldValue(), sim::G4CalorimeterHit::getID(), sim::G4CalorimeterHit::getPdgCode(), sim::G4CalorimeterHit::getPosition(), event::SimCalorimeterHit::getTime(), sim::G4CalorimeterHit::getTime(), sim::G4CalorimeterHit::getTrackID(), hexReadout_, event::SimCalorimeterHit::setEdep(), event::SimCalorimeterHit::setID(), event::SimCalorimeterHit::setPosition(), detdescr::DetectorID::setRawValue(), event::SimCalorimeterHit::setTime(), simParticleBuilder_, detdescr::DetectorID::unpack(), and event::SimCalorimeterHit::updateContrib().
Referenced by sim::RootPersistencyManager::writeHitsCollections().
{
     int nHits = hc->GetSize();
     std::map<int, event::SimCalorimeterHit*> hitMap;
     // Loop over input hits from Geant4.
     for (int iHit = 0; iHit < nHits; iHit++) {
         // Get the hit and its ID.
         G4CalorimeterHit* g4hit = (G4CalorimeterHit*) hc->GetHit(iHit);
         int hitID = g4hit->getID();
         // See if hit exists in map already.
         std::map<int, event::SimCalorimeterHit*>::iterator it = hitMap.find(hitID);
         SimCalorimeterHit* simHit;
         // Is it a new hit?
         if (it == hitMap.end()) {
             // Create sim hit and assign the ID.
             simHit = (SimCalorimeterHit*) outputColl->ConstructedAt(outputColl->GetEntries());
             simHit->setID(hitID);
             detID_.setRawValue(hitID);
             detID_.unpack();
             int cellID = detID_.getFieldValue("cell");
             std::pair<float,float> XYPair = hexReadout_.getCellCentroidXYPair(cellID);
             simHit->setPosition(XYPair.first, XYPair.second, g4hit->getPosition().z());
             hitMap[hitID] = simHit;
         } else {
             // Get existing hit from map.
             simHit = hitMap[hitID];
         }
         // Get info from the G4 hit.
         float edep = g4hit->getEdep();
         float time = g4hit->getTime();
         int pdgCode = g4hit->getPdgCode();
         // Is hit contrib output enabled?
         if (enableHitContribs_) {
             // Find the SimParticle associated with this hit.
             SimParticle* simParticle = simParticleBuilder_->findSimParticle(g4hit->getTrackID());
             // Find if there is an existing hit contrib.
             int contribIndex = simHit->findContribIndex(simParticle, pdgCode);
             // Is contrib output being compressed and a record exists for this SimParticle and PDG code?
             if (compressHitContribs_ && contribIndex != -1) {
                 // Update an existing hit contrib.
                 simHit->updateContrib(contribIndex, edep, time);
                 //std::cout << "updated contrib for hit with ID " << hitID << " with PDGID = "
                 //        << pdgCode << ", edep = " << edep << ", time = " << time << std::endl;;
             } else {
                 // Add a hit contrib because all steps are being saved or there is not an existing record.
                 simHit->addContrib(simParticle, pdgCode, edep, time);
                 //std::cout << "added new contrib for hit with ID " << hitID << " with PDGID = "
                 //        << pdgCode << ", edep = " << edep << ", time = " << time << std::endl;
             }
         } else {
             // Hit contributions are not being saved so manually increment the edep and set time.
             simHit->setEdep(simHit->getEdep() + edep);
             if (time < simHit->getTime() || simHit->getTime() == 0) {
                 simHit->setTime(time);
             }
             //std::cout << "updated hit with ID " << hitID << " with edep = " << edep << ", time = " << time << std::endl;
         }
     }
 }
Member Data Documentation
bool sim::EcalHitIO::compressHitContribs_ {true} private
Enable compression of hit contributions by SimParticle and PDG code.
Definition at line 119 of file EcalHitIO.h.
Referenced by setCompressHitContribs(), and writeHitsCollection().
EcalDetectorID sim::EcalHitIO::detID_ private
ECal detector ID.
Definition at line 109 of file EcalHitIO.h.
Referenced by writeHitsCollection().
bool sim::EcalHitIO::enableHitContribs_ {true} private
Enable hit contribution output.
Definition at line 114 of file EcalHitIO.h.
Referenced by setEnableHitContribs(), and writeHitsCollection().
EcalHexReadout sim::EcalHitIO::hexReadout_ private
Hex cell readout.
Definition at line 104 of file EcalHitIO.h.
Referenced by writeHitsCollection().
SimParticleBuilder* sim::EcalHitIO::simParticleBuilder_ private
Access to SimParticle list.
Definition at line 99 of file EcalHitIO.h.
Referenced by writeHitsCollection().
The documentation for this class was generated from the following files:
SimApplication/include/SimApplication/EcalHitIO.h
SimApplication/src/EcalHitIO.cxx