LDMX Software: detdescr::DefaultDetectorID Class Reference
detdescr::DefaultDetectorID Class Reference
Defines a default detector ID with encoded layer and subdetector values.
#include <DefaultDetectorID.h>
Public Member Functions
DefaultDetectorID ()
int getSubdetID ()
int getLayerID ()
Public Member Functions inherited from detdescr::DetectorID
DetectorID (IDField::IDFieldList *fieldList)
virtual ~DetectorID ()
RawValue getRawValue ()
void setRawValue (RawValue rawValue)
const FieldValueList & unpack ()
RawValue pack ()
FieldValue getFieldValue (int i)
void setFieldValue (int i, FieldValue value)
void setFieldValue (const std::string &fieldName, FieldValue fieldValue)
IDField::IDFieldList * getFieldList ()
IDField * getField (const std::string &fieldName)
FieldValue getFieldValue (const std::string &fieldName)
Additional Inherited Members
Public Types inherited from detdescr::DetectorID
typedef unsigned RawValue
typedef unsigned FieldValue
typedef std::vector< FieldValue > FieldValueList
Protected Member Functions inherited from detdescr::DetectorID
DetectorID ()
void setFieldList (IDField::IDFieldList *fieldList)
void init ()
Protected Attributes inherited from detdescr::DetectorID
RawValue rawValue_
FieldValueList fieldValues_
IDField::IDFieldMap fieldMap_
IDField::IDFieldList * fieldList_
Detailed Description
Defines a default detector ID with encoded layer and subdetector values.
Note
This class provides access to a subdetector ID and layer number.
Definition at line 23 of file DefaultDetectorID.h.
Constructor & Destructor Documentation
detdescr::DefaultDetectorID::DefaultDetectorID ()
Class constructor which adds layer and subdetector fields to the ID definition.
Definition at line 5 of file DefaultDetectorID.cxx.
References detdescr::DetectorID::setFieldList().
                                      : DetectorID() {
     IDField::IDFieldList* fieldList = new IDField::IDFieldList();
     fieldList->push_back(new IDField("subdet", 0, 0, 3));
     fieldList->push_back(new IDField("layer", 1, 4, 11));
     setFieldList(fieldList);
 }
Member Function Documentation
int detdescr::DefaultDetectorID::getLayerID () inline
Get the layer value.
Returns
The layer value.
Definition at line 44 of file DefaultDetectorID.h.
References detdescr::DetectorID::getFieldValue().
{
             return this->getFieldValue(1);
         }
int detdescr::DefaultDetectorID::getSubdetID () inline
Get the subdetector value.
Returns
The subdetector value.
Definition at line 36 of file DefaultDetectorID.h.
References detdescr::DetectorID::getFieldValue().
{
             return this->getFieldValue(0);
         }
The documentation for this class was generated from the following files:
DetDescr/include/DetDescr/DefaultDetectorID.h
DetDescr/src/DefaultDetectorID.cxx