LDMX Software: sim::UserTrackingAction Class Reference
sim::UserTrackingAction Class Reference
Implementation of user tracking action.
#include <UserTrackingAction.h>
Public Member Functions
UserTrackingAction ()
virtual ~UserTrackingAction ()
void PreUserTrackingAction (const G4Track *aTrack)
void PostUserTrackingAction (const G4Track *aTrack)
Public Member Functions inherited from sim::PluginManagerAccessor
void setPluginManager (PluginManager *pluginManager)
PluginManager * getPluginManager ()
Additional Inherited Members
Protected Attributes inherited from sim::PluginManagerAccessor
PluginManager * pluginManager_
Detailed Description
Implementation of user tracking action.
Definition at line 22 of file UserTrackingAction.h.
Constructor & Destructor Documentation
sim::UserTrackingAction::UserTrackingAction ()
Class constructor.
Definition at line 20 of file UserTrackingAction.cxx.
{
 }
sim::UserTrackingAction::~UserTrackingAction () virtual
Class destructor.
Definition at line 23 of file UserTrackingAction.cxx.
{
 }
Member Function Documentation
void sim::UserTrackingAction::PostUserTrackingAction (const G4Track * aTrack)
Implementation of post-tracking action.
Parameters
aTrack The Geant4 track.
Definition at line 52 of file UserTrackingAction.cxx.
References sim::PluginManager::postTracking().
{
     pluginManager_->postTracking(aTrack);
 }
void sim::UserTrackingAction::PreUserTrackingAction (const G4Track * aTrack)
Implementation of pre-tracking action.
Parameters
aTrack The Geant4 track.
Definition at line 26 of file UserTrackingAction.cxx.
References sim::TrackMap::addSecondary(), sim::TrackMap::getInstance(), sim::PluginManager::preTracking(), and sim::Trajectory::setGenStatus().
{
     // Check if trajectory storage should be turned on or off.
     UserRegionInformation* regionInfo =
             (UserRegionInformation*) aTrack->GetLogicalVolumeAtVertex()->GetRegion()->GetUserInformation();
     if (regionInfo != NULL && !regionInfo->getStoreSecondaries()) {
         fpTrackingManager->SetStoreTrajectory(false);
     } else {
         fpTrackingManager->SetStoreTrajectory(true);
         Trajectory* traj = new Trajectory(aTrack);
         fpTrackingManager->SetTrajectory(traj);
         if (aTrack->GetDynamicParticle()->GetPrimaryParticle() != NULL) {
             G4VUserPrimaryParticleInformation* primaryInfo = aTrack->GetDynamicParticle()->GetPrimaryParticle()->GetUserInformation();
             if (primaryInfo != NULL) {
                 traj->setGenStatus(((UserPrimaryParticleInformation*) primaryInfo)->getHepEvtStatus());
             }
         }
     }
     // Save association between track ID and its parent ID.
     TrackMap::getInstance()->addSecondary(aTrack->GetTrackID(), aTrack->GetParentID());
     pluginManager_->preTracking(aTrack);
 }
The documentation for this class was generated from the following files:
SimApplication/include/SimApplication/UserTrackingAction.h
SimApplication/src/UserTrackingAction.cxx