LDMX Software: sim::EcalSD Class Reference
sim::EcalSD Class Reference
ECal sensitive detector that uses an EcalHexReadout to create the hits.
#include <EcalSD.h>
Public Member Functions
EcalSD (G4String name, G4String theCollectionName, int subdet, DetectorID *detID=new EcalDetectorID)
virtual ~EcalSD ()
G4bool ProcessHits (G4Step *aStep, G4TouchableHistory *ROhist)
Public Member Functions inherited from sim::CalorimeterSD
CalorimeterSD (G4String name, G4String theCollectionName, int subdet, DetectorID *detID)
virtual ~CalorimeterSD ()
void setLayerDepth (int layerDepth)
G4bool ProcessHits (G4Step *aStep, G4TouchableHistory *ROhist)
void Initialize (G4HCofThisEvent *hcEvent)
void EndOfEvent (G4HCofThisEvent *hcEvent)
Private Member Functions
G4ThreeVector getHitPosition (G4Step *aStep)
Private Attributes
EcalHexReadout * hitMap_
std::map< G4VSolid
*, G4Polyhedron * > polyMap_
Additional Inherited Members
Protected Attributes inherited from sim::CalorimeterSD
G4CalorimeterHitsCollection * hitsCollection_
int subdet_
DetectorID * detID_
int layerDepth_ {2}
Detailed Description
ECal sensitive detector that uses an EcalHexReadout to create the hits.
Definition at line 32 of file EcalSD.h.
Constructor & Destructor Documentation
sim::EcalSD::EcalSD (G4String name, G4String theCollectionName, int subdet, DetectorID * detID = new EcalDetectorID)
Class constructor.
Parameters
name The name of the sensitive detector.
theCollectionName The name of the hits collection.
subdet The subdetector ID.
detID The detector ID (defaults to ECal ID).
Definition at line 18 of file EcalSD.cxx.
                                                                                           :
         CalorimeterSD(name, theCollectionName, subdetID, detID), hitMap_(new EcalHexReadout) {
 }
sim::EcalSD::~EcalSD () virtual
Class destructor.
Definition at line 22 of file EcalSD.cxx.
 {;}
Member Function Documentation
G4ThreeVector sim::EcalSD::getHitPosition (G4Step * aStep) private
Return the hit position of a step. X and Y are computed from the midpoint of the step. Z corresponds to the volume's center.
Returns
The hit position from the step.
Todo:
This function is probably slow due to it inspecting the geometry to get the Z position so this should be sped up somehow.
Set initial hit position from midpoint of the step.
Use facet info of the solid for setting Z to the sensor midpoint.
Definition at line 83 of file EcalSD.cxx.
References polyMap_.
Referenced by ProcessHits().
{
     G4StepPoint* prePoint = aStep->GetPreStepPoint();
     G4StepPoint* postPoint = aStep->GetPostStepPoint();
     G4ThreeVector position = 0.5 * (prePoint->GetPosition() + postPoint->GetPosition());
     /*
      * Get the volume position in global coordinates, which for the ECal is the center of
      * the front face of the sensor.
      */
     G4ThreeVector volumePosition = aStep->GetPreStepPoint()->GetTouchableHandle()->GetHistory()
         ->GetTopTransform().Inverse().TransformPoint(G4ThreeVector());
     // Get the solid from this step.
     G4VSolid* solid = prePoint->GetTouchableHandle()->GetVolume()->GetLogicalVolume()->GetSolid();
     auto it = polyMap_.find(solid);
     G4Polyhedron* poly;
     if (it == polyMap_.end()) {
         poly = solid->CreatePolyhedron();
         polyMap_[solid] = poly;
     } else {
         poly = polyMap_[solid];
     }
     G4Point3D iNodes[4];
     G4int n;
     poly->GetFacet(1, n, iNodes);
     G4double zstart = iNodes[1][2];
     G4double zend = iNodes[0][2];
     G4double zmid = (zstart - zend) / 2;
     position.setZ(volumePosition.z() + zmid);
     return position;
 }
G4bool sim::EcalSD::ProcessHits (G4Step * aStep, G4TouchableHistory * ROhist)
Process steps to create hits.
Parameters
aStep The step information.
ROhist The readout history.
Definition at line 24 of file EcalSD.cxx.
References sim::CalorimeterSD::detID_, detdescr::EcalHexReadout::getCellId(), getHitPosition(), hitMap_, sim::CalorimeterSD::hitsCollection_, sim::CalorimeterSD::layerDepth_, detdescr::DetectorID::pack(), sim::G4CalorimeterHit::Print(), sim::G4CalorimeterHit::setEdep(), detdescr::DetectorID::setFieldValue(), sim::G4CalorimeterHit::setID(), sim::G4CalorimeterHit::setPdgCode(), sim::G4CalorimeterHit::setPosition(), sim::G4CalorimeterHit::setTime(), sim::G4CalorimeterHit::setTrackID(), and sim::CalorimeterSD::subdet_.
{
     // Determine if current particle of this step is a Geantino.
     G4ParticleDefinition* pdef = aStep->GetTrack()->GetDefinition();
     bool isGeantino = false;
     if (pdef == G4Geantino::Definition() || pdef == G4ChargedGeantino::Definition()) {
         isGeantino = true;
     }
     // Get the edep from the step.
     G4double edep = aStep->GetTotalEnergyDeposit();
     // Skip steps with no energy dep which come from non-Geantino particles.
     if (edep == 0.0 && !isGeantino) {
         if (verboseLevel > 2) {
             std::cout << "CalorimeterSD skipping step with zero edep." << std::endl << std::endl;
         }
         return false;
     }
     // Create a new cal hit.
     G4CalorimeterHit* hit = new G4CalorimeterHit();
     // Set the edep.
     hit->setEdep(edep);
     // Compute the hit position using the utility function.
     G4ThreeVector hitPosition = getHitPosition(aStep);
     hit->setPosition(hitPosition.x(), hitPosition.y(), hitPosition.z());
     // Set the global time.
     hit->setTime(aStep->GetTrack()->GetGlobalTime());
     // Create the ID for the hit.
     int layerNumber = aStep->GetPreStepPoint()->GetTouchableHandle()->GetHistory()->GetVolume(layerDepth_)->GetCopyNo();
     int cellID = hitMap_->getCellId(hitPosition[0], hitPosition[1]);
     detID_->setFieldValue(1, layerNumber);
     detID_->setFieldValue(2, cellID);
     hit->setID(detID_->pack());
     // Set the track ID on the hit.
     hit->setTrackID(aStep->GetTrack()->GetTrackID());
     // Set the PDG code from the track.
     hit->setPdgCode(aStep->GetTrack()->GetParticleDefinition()->GetPDGEncoding());
     if (this->verboseLevel > 2) {
         std::cout << "Created new SimCalorimeterHit in detector " << this->GetName()
                 << " with subdet ID " << subdet_ << " and layer " << layerNumber << " and cellid " << cellID << " ..." ;
         hit->Print();
         std::cout << std::endl;
     }
     // Insert the hit into the hits collection.
     hitsCollection_->insert(hit);
     return true;
 }
Member Data Documentation
EcalHexReadout* sim::EcalSD::hitMap_ private
The hex readout defining the cell grid.
Definition at line 77 of file EcalSD.h.
Referenced by ProcessHits().
std::map<G4VSolid*, G4Polyhedron*> sim::EcalSD::polyMap_ private
Map of polygonal layers for getting Z positions.
Definition at line 82 of file EcalSD.h.
Referenced by getHitPosition().
The documentation for this class was generated from the following files:
SimApplication/include/SimApplication/EcalSD.h
SimApplication/src/EcalSD.cxx