LDMX Software: sim::RootPersistencyManager Class Reference
sim::RootPersistencyManager Class Reference
Provides a G4PersistencyManager implemention with SimEvent output.
#include <RootPersistencyManager.h>
Public Types
typedef std::map< std::string,
TClonesArray * > HitsCollectionMap
Public Member Functions
RootPersistencyManager ()
G4bool Store (const G4Event *anEvent)
G4bool Store (const G4Run *aRun)
G4bool Store (const G4VPhysicalVolume *)
void Initialize ()
void setFileName (std::string fileName)
void setEnableHitContribs (bool enableHitContribs)
void setCompressHitContribs (bool compressHitContribs)
void setCompressionLevel (int compressionLevel)
Static Public Member Functions
static RootPersistencyManager * getInstance ()
Private Member Functions
void buildEvent (const G4Event *anEvent, event::Event *outputEvent)
void writeHeader (const G4Event *anEvent, event::Event *outputEvent)
void writeHitsCollections (const G4Event *anEvent, event::Event *outputEvent)
void writeTrackerHitsCollection (G4TrackerHitsCollection *hc, TClonesArray *outputColl)
void writeCalorimeterHitsCollection (G4CalorimeterHitsCollection *hc, TClonesArray *outputColl)
void printEvent (event::Event *anEvent)
void setupHitsCollectionMap ()
event::RunHeader * createRunHeader (const G4Run *aRun)
void writeRunHeader (const G4Run *aRun)
Private Attributes
std::string fileName_ {"ldmx_sim_events.root"}
ldmxsw::EventFile * outputFile_ {nullptr}
int compressionLevel_ {6}
event::Event * event_ {nullptr}
event::EventHeader eventHeader_
EcalHitIO * ecalHitIO_
SimParticleBuilder simParticleBuilder_
HitsCollectionMap outputHitsCollections_
Detailed Description
Provides a G4PersistencyManager implemention with SimEvent output.
Note
Output is written at the end of each event. An EventFile is used to write from an Event buffer object into an output branch within a tree. The event buffer is cleared after the event is written. A SimParticleBuilder is used to build a set of SimParticle objects from the Trajectory objects which were created during event processing. An EcalHitIO instance provides translation of G4CalorimeterHit objects in the ECal to an output SimCalorimeterHit collection, transforming the individual steps into cell energy depositions. The tracker hit collections of G4TrackerHit objects are translated directly into output SimTrackerHit collections.
Definition at line 40 of file RootPersistencyManager.h.
Constructor & Destructor Documentation
sim::RootPersistencyManager::RootPersistencyManager ()
Class constructor. Installs the object as the global persistency manager.
Definition at line 25 of file RootPersistencyManager.cxx.
References event_.
                                                :
         G4PersistencyManager(G4PersistencyCenter::GetPersistencyCenter(), "RootPersistencyManager"),
         ecalHitIO_(new EcalHitIO(&simParticleBuilder_)) {
     G4PersistencyCenter::GetPersistencyCenter()->RegisterPersistencyManager(this);
     G4PersistencyCenter::GetPersistencyCenter()->SetPersistencyManager(this, "RootPersistencyManager");
     event_ = new ldmxsw::EventImpl("sim");
 }
Member Function Documentation
void sim::RootPersistencyManager::buildEvent (const G4Event * anEvent, event::Event * outputEvent) private
Build an output event from the current Geant4 event.
Parameters
anEvent The Geant4 event.
outputEvent The output event.
Definition at line 95 of file RootPersistencyManager.cxx.
References sim::SimParticleBuilder::buildSimParticles(), sim::SimParticleBuilder::setCurrentEvent(), simParticleBuilder_, writeHeader(), and writeHitsCollections().
Referenced by Store().
{
     // Set basic event information.
     writeHeader(anEvent, outputEvent);
     // Set pointer to current G4Event.
     simParticleBuilder_.setCurrentEvent(anEvent);
     // Build the SimParticle list for the output ROOT event.
     simParticleBuilder_.buildSimParticles(outputEvent);
     // Copy hit objects from SD hit collections into the output event.
     writeHitsCollections(anEvent, outputEvent);
 }
event::RunHeader * sim::RootPersistencyManager::createRunHeader (const G4Run * aRun) private
Create the run header for writing into the output file.
Parameters
aRun The current Geant4 run.
Returns
The created run header.
Definition at line 250 of file RootPersistencyManager.cxx.
References event::RunHeader::getDescription(), sim::DetectorConstruction::getDetectorHeader(), event::RunHeader::getDetectorName(), event::RunHeader::getDetectorVersion(), detdescr::DetectorHeader::getName(), event::RunHeader::getRunNumber(), detdescr::DetectorHeader::getVersion(), and event::RunHeader::setIntParameter().
Referenced by writeRunHeader().
{
     // Get detector header from the user detector construction.
     DetectorConstruction* detector =
             ((RunManager*)RunManager::GetRunManager())->getDetectorConstruction();
     detdescr::DetectorHeader* detectorHeader = detector->getDetectorHeader();
     // Create the run header.
     event::RunHeader* runHeader =
             new event::RunHeader(aRun->GetRunID(),
                     detectorHeader->getName(),
                     detectorHeader->getVersion(),
                     "LDMX sim events");
     // Set parameter value with number of events processed.
     runHeader->setIntParameter("EVENT_COUNT", aRun->GetNumberOfEvent());
     // Print information about run header.
     if (m_verbose > 1) {
         std::cout << std::endl;
         std::cout << "[ RootPersistencyManager ] - Created run header for run ID " << aRun->GetRunID() << std::endl;
         std::cout << "  run number: " << runHeader->getRunNumber() << std::endl;
         std::cout << "  detector name: " << runHeader->getDetectorName() << std::endl;
         std::cout << "  detector version: " << runHeader->getDetectorVersion() << std::endl;
         std::cout << "  description: " << runHeader->getDescription() << std::endl;
         std::cout << std::endl;
     }
     return runHeader;
 }
static RootPersistencyManager* sim::RootPersistencyManager::getInstance () inline static
Get the current ROOT persistency manager or nullptr if not registered.
Returns
The ROOT persistency manager.
Definition at line 62 of file RootPersistencyManager.h.
Referenced by sim::UserRunAction::BeginOfRunAction(), and sim::RootPersistencyMessenger::SetNewValue().
{
             return (RootPersistencyManager*) G4PersistencyCenter::GetPersistencyCenter()->CurrentPersistencyManager();
         }
void sim::RootPersistencyManager::Initialize ()
This is called "manually" in UserRunAction to open the ROOT writer for the run.
Definition at line 81 of file RootPersistencyManager.cxx.
References compressionLevel_, event_, fileName_, outputFile_, ldmxsw::EventFile::setupEvent(), and setupHitsCollectionMap().
Referenced by sim::UserRunAction::BeginOfRunAction().
{
     if (m_verbose > 1) {
         std::cout << "[ RootPersistencyManager ] : Opening output file " << fileName_ << std::endl;
     }
     // Create and setup the output file for writing the events.
     outputFile_ = new ldmxsw::EventFile(fileName_.c_str(), true, compressionLevel_);
     outputFile_->setupEvent((ldmxsw::EventImpl*)event_);
     // Create map with output hits collections.
     setupHitsCollectionMap();
 }
void sim::RootPersistencyManager::printEvent (event::Event * anEvent) private
Print out event info and data depending on the verbose level.
Parameters
anEvent The output event.
Definition at line 110 of file RootPersistencyManager.cxx.
References event::Event::get(), and outputHitsCollections_.
Referenced by Store().
{
     if (m_verbose > 2) {
         auto particleColl = outputEvent->get<TClonesArray*>("SimParticles", "sim");
         if (!particleColl) {
             throw std::runtime_error("SimParticle output collection is null!");
         }
         std::cout << std::endl;
         std::cout << "[ RootPersistencyManager ] - Printing SimParticle collection" << std::endl;
         for (int iColl = 0; iColl < particleColl->GetEntriesFast(); iColl++) {
             particleColl->At(iColl)->Print();
         }
         std::cout << std::endl;
         for (auto entry : outputHitsCollections_) {
             std::cout << "[ RootPersistencyManager ] - Printing collection " << entry.first << std::endl;
             TClonesArray* hitsColl = entry.second;
             int entries = hitsColl->GetEntriesFast();
             for (int iColl = 0; iColl < entries; iColl++) {
                 TObject* obj = (*hitsColl)[iColl];
                 obj->Print("");
             }
         }
         std::cout << std::endl;
     }
 }
void sim::RootPersistencyManager::setCompressHitContribs (bool compressHitContribs) inline
Enable or disable compression of hit contribution output by finding matching SimParticle and PDG codes and updating the existing record. This is enabled by default.
Parameters
compressHitContribs True to compress hit contributions.
Definition at line 115 of file RootPersistencyManager.h.
References ecalHitIO_, and sim::EcalHitIO::setCompressHitContribs().
Referenced by sim::RootPersistencyMessenger::SetNewValue().
{
             // Pass this flag to the ECal IO helper.
             ecalHitIO_->setCompressHitContribs(compressHitContribs);
         }
void sim::RootPersistencyManager::setEnableHitContribs (bool enableHitContribs) inline
Enable or disable hit contribution output for SimCalorimeterHits. This is enabled by default.
Parameters
enableHitContribs True to enable hit contributions.
Definition at line 104 of file RootPersistencyManager.h.
References ecalHitIO_, and sim::EcalHitIO::setEnableHitContribs().
Referenced by sim::RootPersistencyMessenger::SetNewValue().
{
             // Pass this flag to the ECal IO helper.
             ecalHitIO_->setEnableHitContribs(enableHitContribs);
         }
void sim::RootPersistencyManager::setFileName (std::string fileName) inline
Set the output file name.
Parameters
fileName The output file name.
Definition at line 94 of file RootPersistencyManager.h.
References fileName_.
Referenced by sim::RootPersistencyMessenger::SetNewValue().
{
             fileName_ = fileName;
         }
void sim::RootPersistencyManager::setupHitsCollectionMap () private
Setup a map of HC names to output TClonesArray collections. This is called once at the beginning of the run.
Definition at line 281 of file RootPersistencyManager.cxx.
References outputHitsCollections_.
Referenced by Initialize().
{
     // Clear any state from the last run.
     if (outputHitsCollections_.size()) {
         for (auto entry : outputHitsCollections_) {
             delete entry.second;
         }
     }
     outputHitsCollections_.clear();
     // Create an output TClonesArray in the map for each registered HC.
     G4SDManager* sdMgr = G4SDManager::GetSDMpointer();
     G4HCtable* hcTable = sdMgr->GetHCtable();
     int entries = hcTable->entries();
     for (int i = 0; i < entries; i++) {
         std::string sdName = hcTable->GetSDname(i);
         std::string hcName = hcTable->GetHCname(i);
         G4VSensitiveDetector* sd = sdMgr->FindSensitiveDetector(sdName);
         if (dynamic_cast<CalorimeterSD*>(sd)) {
             outputHitsCollections_[hcName] = new TClonesArray("event::SimCalorimeterHit", 500);
             if (m_verbose > 1) {
                 std::cout << "[ RootPersistencyManager ] - Created SimCalorimeterHit HC " << hcName << std::endl;
             }
         } else if (dynamic_cast<TrackerSD*>(sd)) {
             outputHitsCollections_[hcName] = new TClonesArray("event::SimTrackerHit", 50);
             if (m_verbose > 1) {
                 std::cout << "[ RootPersistencyManager ] - Created SimTrackerHit HC " << hcName << std::endl;
             }
         }
     }
 }
G4bool sim::RootPersistencyManager::Store (const G4Event * anEvent)
Builds the output ROOT event.
Parameters
anEvent The Geant4 event data.
Definition at line 34 of file RootPersistencyManager.cxx.
References buildEvent(), event_, ldmxsw::EventFile::nextEvent(), outputFile_, and printEvent().
{
     // verbose level 2
     if (m_verbose > 1) {
         std::cout << "[ RootPersistencyManager ] : Storing event " << anEvent->GetEventID() << std::endl;
     }
     if (G4RunManager::GetRunManager()->GetCurrentEvent()->IsAborted()) {
         // TODO: Need event cleanup here?
         return false;
     }
     // Build the output collections.
     buildEvent(anEvent, event_);
     // Print out event info and data depending on verbose level.
     printEvent(event_);
     outputFile_->nextEvent();
     return true;
 }
G4bool sim::RootPersistencyManager::Store (const G4Run * aRun)
This gets called automatically at the end of the run and is used to write out the run header and close the writer.
Parameters
aRun The Geant4 run data.
Returns
True if event is stored (function is hard-coded to return true).
Definition at line 65 of file RootPersistencyManager.cxx.
References ldmxsw::EventFile::close(), outputFile_, and writeRunHeader().
{
     if (m_verbose > 1) {
         std::cout << "[ RootPersistencyManager ] : Storing run " << aRun->GetRunID() << std::endl;
     }
     // Write out the run header.
     writeRunHeader(aRun);
     // Close the file and delete the output file object.
     outputFile_->close();
     delete outputFile_;
     outputFile_ = nullptr;
     return true;
 }
G4bool sim::RootPersistencyManager::Store (const G4VPhysicalVolume *) inline
Implementing this makes an "overloaded-virtual" compiler warning go away.
Definition at line 83 of file RootPersistencyManager.h.
 { return false; }
void sim::RootPersistencyManager::writeCalorimeterHitsCollection (G4CalorimeterHitsCollection * hc, TClonesArray * outputColl) private
Write a collection of tracker hits to an output collection.
Parameters
hc The collection of G4CalorimeterHits.
outputColl The output collection of SimCalorimeterHits.
Definition at line 237 of file RootPersistencyManager.cxx.
References event::SimCalorimeterHit::addContrib(), sim::SimParticleBuilder::findSimParticle(), sim::G4CalorimeterHit::getEdep(), sim::G4CalorimeterHit::getID(), sim::G4CalorimeterHit::getPdgCode(), sim::G4CalorimeterHit::getPosition(), sim::G4CalorimeterHit::getTime(), sim::G4CalorimeterHit::getTrackID(), event::SimCalorimeterHit::setID(), event::SimCalorimeterHit::setPosition(), and simParticleBuilder_.
Referenced by writeHitsCollections().
{
     int nHits = hc->GetSize();
     for (int iHit = 0; iHit < nHits; iHit++) {
         G4CalorimeterHit* g4hit = (G4CalorimeterHit*) hc->GetHit(iHit);
         SimCalorimeterHit* simHit = (SimCalorimeterHit*) outputColl->ConstructedAt(outputColl->GetEntries());
         simHit->setID(g4hit->getID());
         const G4ThreeVector& pos = g4hit->getPosition();
         simHit->setPosition(pos.x(), pos.y(), pos.z());
         SimParticle* particle = simParticleBuilder_.findSimParticle(g4hit->getTrackID());
         simHit->addContrib(particle, g4hit->getPdgCode(), g4hit->getEdep(), g4hit->getTime());
     }
 }
void sim::RootPersistencyManager::writeHeader (const G4Event * anEvent, event::Event * outputEvent) private
Write header info into the output event from Geant4.
Parameters
anEvent The Geant4 event.
outputEvent The output event.
Definition at line 137 of file RootPersistencyManager.cxx.
References event::EventHeader::Print(), event::EventHeader::setEventNumber(), event::EventHeader::setRun(), event::EventHeader::setTimestamp(), and event::EventHeader::setWeight().
Referenced by buildEvent().
{
     event::EventHeader& eventHeader = ((ldmxsw::EventImpl*)outputEvent)->getEventHeaderMutable();
     eventHeader.setEventNumber(anEvent->GetEventID());
     TTimeStamp ts;
     ts.SetSec((int) time(NULL));
     eventHeader.setTimestamp(ts);
     eventHeader.setRun(G4RunManager::GetRunManager()->GetCurrentRun()->GetRunID());
     if (anEvent->GetPrimaryVertex(0)) {
         eventHeader.setWeight(anEvent->GetPrimaryVertex(0)->GetWeight());
     }
     if (m_verbose > 1) {
         std::cout << "[ RootPersistencyManager ] : Wrote event header for event ID " << anEvent->GetEventID() << std::endl;
         std::cout << "  ";
         eventHeader.Print("");
     }
 }
void sim::RootPersistencyManager::writeHitsCollections (const G4Event * anEvent, event::Event * outputEvent) private
Write hits collections from Geant4 into a ROOT event.
Parameters
anEvent The Geant4 event.
outputEvent The output event.
Definition at line 156 of file RootPersistencyManager.cxx.
References event::Event::add(), ecalHitIO_, outputHitsCollections_, writeCalorimeterHitsCollection(), sim::EcalHitIO::writeHitsCollection(), and writeTrackerHitsCollection().
Referenced by buildEvent().
{
     // Clear the hits from last event.
     for (auto entry : outputHitsCollections_) {
         entry.second->Clear("C");
     }
     // Get the HC of this event.
     G4HCofThisEvent* hce = anEvent->GetHCofThisEvent();
     int nColl = hce->GetNumberOfCollections();
     // Loop over all hits collections.
     for (int iColl = 0; iColl < nColl; iColl++) {
         // Get a hits collection and its name.
         G4VHitsCollection* hc = hce->GetHC(iColl);
         std::string collName = hc->GetName();
         // Get the target output collection.
         TClonesArray* outputHitsColl = outputHitsCollections_[collName];
         // If the collection is not found in the output ROOT event, then a fatal error occurs!
         if (!outputHitsColl) {
             std::cerr << "ERROR: The output collection " << collName << " was not found!" << std::endl;
             G4Exception("RootPersistencyManager::writeHitsCollections",
                     "",
                     FatalException,
                     "The output collection was not found.");
         }
         if (dynamic_cast<G4TrackerHitsCollection*>(hc) != nullptr) {
             // Write G4TrackerHit collection to output SimTrackerHit collection.
             G4TrackerHitsCollection* trackerHitsColl = dynamic_cast<G4TrackerHitsCollection*>(hc);
             writeTrackerHitsCollection(trackerHitsColl, outputHitsColl);
         } else if (dynamic_cast<G4CalorimeterHitsCollection*>(hc) != nullptr) {
             G4CalorimeterHitsCollection* calHitsColl = dynamic_cast<G4CalorimeterHitsCollection*>(hc);
             if (collName == EventConstants::ECAL_SIM_HITS) {
                 // Write ECal G4CalorimeterHit collection to output SimCalorimeterHit collection using helper class.
                 ecalHitIO_->writeHitsCollection(calHitsColl, outputHitsColl);
             } else {
                 // Write generic G4CalorimeterHit collection to output SimCalorimeterHit collection.
                 writeCalorimeterHitsCollection(calHitsColl, outputHitsColl);
             }
         }
         // Add hits collection to output event.
         outputEvent->add(collName, outputHitsColl);
         if (m_verbose > 1) {
             std::cout << "[ RootPersistencyManager ] : Wrote " <<  outputHitsColl->GetEntriesFast() << " hits into " << collName << std::endl;
         }
     }
 }
void sim::RootPersistencyManager::writeRunHeader (const G4Run * aRun) private
Create the run header and write it into the current output file.
Parameters
aRun The current Geant4 run.
Definition at line 57 of file RootPersistencyManager.cxx.
References createRunHeader().
Referenced by Store().
{
     event::RunHeader* runHeader = createRunHeader(aRun);
     TTree* runTree = new TTree("LDMX_Run", "LDMX run header");
     runTree->Branch("LdmxRun", "event::RunHeader", &runHeader, 32000, 3);
     runTree->Fill();
     delete runHeader;
 }
void sim::RootPersistencyManager::writeTrackerHitsCollection (G4TrackerHitsCollection * hc, TClonesArray * outputColl) private
Write a collection of tracker hits to an output collection.
Parameters
hc The collection of G4TrackerHits.
outputColl The output collection of SimTrackerHits.
Definition at line 213 of file RootPersistencyManager.cxx.
References sim::SimParticleBuilder::findSimParticle(), sim::G4TrackerHit::getEdep(), sim::G4TrackerHit::getID(), sim::G4TrackerHit::getLayerID(), sim::G4TrackerHit::getMomentum(), sim::G4TrackerHit::getPathLength(), sim::G4TrackerHit::getPosition(), sim::G4TrackerHit::getTrackID(), event::SimTrackerHit::setEdep(), event::SimTrackerHit::setID(), event::SimTrackerHit::setLayerID(), event::SimTrackerHit::setMomentum(), event::SimTrackerHit::setPathLength(), event::SimTrackerHit::setPosition(), event::SimTrackerHit::setSimParticle(), and simParticleBuilder_.
Referenced by writeHitsCollections().
{
     int nHits = hc->GetSize();
     for (int iHit = 0; iHit < nHits; iHit++) {
         G4TrackerHit* g4hit = (G4TrackerHit*) hc->GetHit(iHit);
         SimTrackerHit* simTrackerHit = (SimTrackerHit*) outputColl->ConstructedAt(outputColl->GetEntries());
         simTrackerHit->setID(g4hit->getID());
         simTrackerHit->setLayerID(g4hit->getLayerID());
         simTrackerHit->setEdep(g4hit->getEdep());
         const G4ThreeVector& momentum = g4hit->getMomentum();
         simTrackerHit->setMomentum(
                 momentum.x(),
                 momentum.y(),
                 momentum.z());
         const G4ThreeVector& position = g4hit->getPosition();
         simTrackerHit->setPosition(
                 position.x(),
                 position.y(),
                 position.z());
         simTrackerHit->setPathLength(g4hit->getPathLength());
         SimParticle* simParticle = simParticleBuilder_.findSimParticle(g4hit->getTrackID());
         simTrackerHit->setSimParticle(simParticle);
     }
 }
Member Data Documentation
int sim::RootPersistencyManager::compressionLevel_ {6} private
Output file compression level.
Definition at line 201 of file RootPersistencyManager.h.
Referenced by Initialize().
EcalHitIO* sim::RootPersistencyManager::ecalHitIO_ private
Handles ECal hit readout and IO.
Definition at line 216 of file RootPersistencyManager.h.
Referenced by setCompressHitContribs(), setEnableHitContribs(), and writeHitsCollections().
event::Event* sim::RootPersistencyManager::event_ {nullptr} private
The event container used to manage the tree/branches/collections.
Definition at line 206 of file RootPersistencyManager.h.
Referenced by Initialize(), RootPersistencyManager(), and Store().
event::EventHeader sim::RootPersistencyManager::eventHeader_ private
Event header for writing out event number, etc. into output.
Definition at line 211 of file RootPersistencyManager.h.
std::string sim::RootPersistencyManager::fileName_ {"ldmx_sim_events.root"} private
The output file name.
Definition at line 191 of file RootPersistencyManager.h.
Referenced by Initialize(), and setFileName().
ldmxsw::EventFile* sim::RootPersistencyManager::outputFile_ {nullptr} private
The output file with the event tree.
Definition at line 196 of file RootPersistencyManager.h.
Referenced by Initialize(), and Store().
HitsCollectionMap sim::RootPersistencyManager::outputHitsCollections_ private
Map of HC names to output TClonesArray collection.
Definition at line 226 of file RootPersistencyManager.h.
Referenced by printEvent(), setupHitsCollectionMap(), and writeHitsCollections().
SimParticleBuilder sim::RootPersistencyManager::simParticleBuilder_ private
Helper for building output SimParticle collection.
Definition at line 221 of file RootPersistencyManager.h.
Referenced by buildEvent(), writeCalorimeterHitsCollection(), and writeTrackerHitsCollection().
The documentation for this class was generated from the following files:
SimApplication/include/SimApplication/RootPersistencyManager.h
SimApplication/src/RootPersistencyManager.cxx