LDMX Software: sim::VisAttributesStore Class Reference
sim::VisAttributesStore Class Reference
Global store of G4VisAttributes created from GDML data.
#include <VisAttributesStore.h>
Public Types
typedef std::map< std::string,
G4VisAttributes * > VisAttributesMap
Public Member Functions
G4VisAttributes * getVisAttributes (const std::string &name)
void addVisAttributes (const std::string &name, G4VisAttributes *visAttributes)
Static Public Member Functions
static VisAttributesStore * getInstance ()
Private Attributes
VisAttributesMap visAttributesMap_
Detailed Description
Global store of G4VisAttributes created from GDML data.
Definition at line 19 of file VisAttributesStore.h.
Member Typedef Documentation
typedef std::map<std::string, G4VisAttributes*> sim::VisAttributesStore::VisAttributesMap
Map of name to vis attributes.
Definition at line 26 of file VisAttributesStore.h.
Member Function Documentation
void sim::VisAttributesStore::addVisAttributes (const std::string & name, G4VisAttributes * visAttributes) inline
Register a vis attributes by name.
Parameters
name The name of the vis attributes.
visAttributes The vis attributes to register.
Definition at line 51 of file VisAttributesStore.h.
References visAttributesMap_.
Referenced by sim::AuxInfoReader::createVisAttributes().
{
             visAttributesMap_[name] = visAttributes;
         }
static VisAttributesStore* sim::VisAttributesStore::getInstance () inline static
Get the global instance of the store.
Returns
The vis attributes store.
Definition at line 32 of file VisAttributesStore.h.
Referenced by sim::AuxInfoReader::assignAuxInfoToVolumes(), and sim::AuxInfoReader::createVisAttributes().
{
             static VisAttributesStore INSTANCE;
             return &INSTANCE;
         }
G4VisAttributes* sim::VisAttributesStore::getVisAttributes (const std::string & name) inline
Get vis attributes by name.
Parameters
name The name of the vis attributes.
Returns
The vis attributes or nullptr if does not exist.
Definition at line 42 of file VisAttributesStore.h.
References visAttributesMap_.
Referenced by sim::AuxInfoReader::assignAuxInfoToVolumes().
{
             return visAttributesMap_[name];
         }
Member Data Documentation
VisAttributesMap sim::VisAttributesStore::visAttributesMap_ private
The map of names to vis attributes.
Definition at line 60 of file VisAttributesStore.h.
Referenced by addVisAttributes(), and getVisAttributes().
The documentation for this class was generated from the following file:
SimApplication/include/SimApplication/VisAttributesStore.h