LDMX Software: sim::UserActionPlugin Class Reference
sim::UserActionPlugin Class Reference abstract
User simulation plugin.
#include <UserActionPlugin.h>
Public Member Functions
virtual ~UserActionPlugin ()
virtual std::string getName ()=0
void setVerboseLevel (int verbose)
int getVerboseLevel ()
virtual bool hasRunAction ()
virtual bool hasSteppingAction ()
virtual bool hasTrackingAction ()
virtual bool hasEventAction ()
virtual bool hasStackingAction ()
virtual bool hasPrimaryGeneratorAction ()
virtual void beginRun (const G4Run *)
virtual void endRun (const G4Run *)
virtual void stepping (const G4Step *)
virtual void preTracking (const G4Track *)
virtual void postTracking (const G4Track *)
virtual void beginEvent (const G4Event *)
virtual void endEvent (const G4Event *)
virtual void generatePrimary (G4Event *)
virtual G4ClassificationOfNewTrack stackingClassifyNewTrack (const G4Track *, const G4ClassificationOfNewTrack &currentTrackClass)
virtual void stackingNewStage ()
virtual void stackingPrepareNewEvent ()
Protected Attributes
int verbose_ {1}
Detailed Description
User simulation plugin.
Note
This class defines a plugin interface to the Geant4 simulation engine which is activated in the "user action" hooks. An implementation class must define "create" and "destroy" functions as entry points for the dynamic library loading. By default, the plugin does not activate any of the user actions, and the user should override the methods which return boolean flags to activate these hooks.
Here are examples of the static functions that should be defined for creating and destroying the plugin in the class's source file, assuming that the plugin is called DummySimPlugin.
Example create function:
Example destroy function:
Definition at line 43 of file UserActionPlugin.h.
Constructor & Destructor Documentation
virtual sim::UserActionPlugin::~UserActionPlugin () inline virtual
Class destructor.
Definition at line 50 of file UserActionPlugin.h.
 {;}
Member Function Documentation
virtual void sim::UserActionPlugin::beginEvent (const G4Event *) inline virtual
Begin of event action.
Reimplemented in sim::DummySimPlugin.
Definition at line 144 of file UserActionPlugin.h.
 {;}
virtual void sim::UserActionPlugin::beginRun (const G4Run *) inline virtual
Begin of run action.
Reimplemented in sim::EventPrintPlugin, sim::PhotonuclearXsecBiasingPlugin, and sim::DummySimPlugin.
Definition at line 119 of file UserActionPlugin.h.
 {;}
virtual void sim::UserActionPlugin::endEvent (const G4Event *) inline virtual
End of event action.
Reimplemented in sim::EventPrintPlugin, and sim::DummySimPlugin.
Definition at line 149 of file UserActionPlugin.h.
 {;}
virtual void sim::UserActionPlugin::endRun (const G4Run *) inline virtual
End of run action.
Reimplemented in sim::EventPrintPlugin, and sim::DummySimPlugin.
Definition at line 124 of file UserActionPlugin.h.
 {;}
virtual void sim::UserActionPlugin::generatePrimary (G4Event *) inline virtual
Generate primary action.
Reimplemented in sim::DummySimPlugin, and sim::EventPrintPlugin.
Definition at line 154 of file UserActionPlugin.h.
 {;}
virtual std::string sim::UserActionPlugin::getName () pure virtual
Get the name of the plugin. The user must override this function.
Returns
The name of the plugin.
Implemented in sim::EventPrintPlugin, sim::PhotonuclearXsecBiasingPlugin, sim::TargetPhotonuclearBiasingPlugin, and sim::DummySimPlugin.
Referenced by sim::PluginLoader::destroy(), sim::UserActionPluginMessenger::SetNewValue(), and sim::UserActionPluginMessenger::UserActionPluginMessenger().
int sim::UserActionPlugin::getVerboseLevel () inline
Get the current verbose level.
Returns
The current verbose level.
Definition at line 76 of file UserActionPlugin.h.
References verbose_.
Referenced by sim::UserActionPluginMessenger::SetNewValue().
{
             return verbose_;
         }
virtual bool sim::UserActionPlugin::hasEventAction () inline virtual
Get whether this plugin implements the event action.
Returns
True if the plugin implements the event action.
Reimplemented in sim::EventPrintPlugin, and sim::DummySimPlugin.
Definition at line 102 of file UserActionPlugin.h.
 { return false; }
virtual bool sim::UserActionPlugin::hasPrimaryGeneratorAction () inline virtual
Get whether this plugin implements the primary generator action.
Returns
True if the plugin implements the primary generator action.
Reimplemented in sim::EventPrintPlugin, and sim::DummySimPlugin.
Definition at line 114 of file UserActionPlugin.h.
 { return false; }
virtual bool sim::UserActionPlugin::hasRunAction () inline virtual
Get whether this plugin implements the run action.
Returns
True if the plugin implements the run action.
Reimplemented in sim::EventPrintPlugin, sim::PhotonuclearXsecBiasingPlugin, and sim::DummySimPlugin.
Definition at line 84 of file UserActionPlugin.h.
 { return false; }
virtual bool sim::UserActionPlugin::hasStackingAction () inline virtual
Get whether this plugin implements the stacking action.
Returns
True if the plugin implements the stacking action.
Reimplemented in sim::TargetPhotonuclearBiasingPlugin, and sim::DummySimPlugin.
Definition at line 108 of file UserActionPlugin.h.
 { return false; }
virtual bool sim::UserActionPlugin::hasSteppingAction () inline virtual
Get whether this plugin implements the stepping action.
Returns
True if the plugin implements the stepping action.
Reimplemented in sim::TargetPhotonuclearBiasingPlugin, and sim::DummySimPlugin.
Definition at line 90 of file UserActionPlugin.h.
 { return false; }
virtual bool sim::UserActionPlugin::hasTrackingAction () inline virtual
Get whether this plugin implements the tracking action.
Returns
True if the plugin implements the tracking action.
Reimplemented in sim::DummySimPlugin.
Definition at line 96 of file UserActionPlugin.h.
 { return false; }
virtual void sim::UserActionPlugin::postTracking (const G4Track *) inline virtual
Post-tracking action.
Reimplemented in sim::DummySimPlugin.
Definition at line 139 of file UserActionPlugin.h.
 {;}
virtual void sim::UserActionPlugin::preTracking (const G4Track *) inline virtual
Pre-tracking action.
Reimplemented in sim::DummySimPlugin.
Definition at line 134 of file UserActionPlugin.h.
 {;}
void sim::UserActionPlugin::setVerboseLevel (int verbose) inline
Set the verbose level of the plugin (1-4).
Parameters
verbose The verbose level of the plugin.
Definition at line 63 of file UserActionPlugin.h.
References verbose_.
Referenced by sim::UserActionPluginMessenger::SetNewValue().
{
             verbose_ = verbose;
             if (verbose_ < 1) {
                 verbose = 1;
             } else if (verbose_ > 4) {
                 verbose = 4;
             }
         }
virtual G4ClassificationOfNewTrack sim::UserActionPlugin::stackingClassifyNewTrack (const G4Track * , const G4ClassificationOfNewTrack & currentTrackClass) inline virtual
Classify a new track.
Parameters
currentTrackClass The current track classification.
Returns
The current track classification returned by default.
Reimplemented in sim::DummySimPlugin, and sim::TargetPhotonuclearBiasingPlugin.
Definition at line 161 of file UserActionPlugin.h.
{
             return currentTrackClass;
         }
virtual void sim::UserActionPlugin::stackingNewStage () inline virtual
New stacking stage action.
Reimplemented in sim::DummySimPlugin.
Definition at line 168 of file UserActionPlugin.h.
 {;}
virtual void sim::UserActionPlugin::stackingPrepareNewEvent () inline virtual
New event stacking action.
Reimplemented in sim::DummySimPlugin.
Definition at line 173 of file UserActionPlugin.h.
 {;}
virtual void sim::UserActionPlugin::stepping (const G4Step *) inline virtual
Stepping action.
Reimplemented in sim::TargetPhotonuclearBiasingPlugin, and sim::DummySimPlugin.
Definition at line 129 of file UserActionPlugin.h.
 {;}
Member Data Documentation
int sim::UserActionPlugin::verbose_ {1} protected
Protected access to verbose level for convenience of sub-classes.
Definition at line 178 of file UserActionPlugin.h.
Referenced by getVerboseLevel(), and setVerboseLevel().
The documentation for this class was generated from the following file:
SimPlugins/include/SimPlugins/UserActionPlugin.h