LDMX Software: event::EventHeader Class Reference
event::EventHeader Class Reference
Provides header information an event such as event number and timestamp.
#include <EventHeader.h>
Public Member Functions
EventHeader ()
virtual ~EventHeader ()
void Clear (Option_t *="")
void Print (Option_t *="") const
void Copy (TObject &o) const
int getEventNumber () const
int getRun () const
const TTimeStamp & getTimestamp () const
double getWeight () const
bool isRealData () const
void setEventNumber (int eventNumber)
void setRun (int run)
void setTimestamp (const TTimeStamp &timestamp)
void setWeight (double weight)
Protected Member Functions
ClassDef (EventHeader, 1)
Protected Attributes
int eventNumber_ {-1}
int run_ {-1}
TTimeStamp timestamp_ {0, 0}
double weight_ {1.0}
bool isRealData_ {false}
Detailed Description
Provides header information an event such as event number and timestamp.
Definition at line 20 of file EventHeader.h.
Constructor & Destructor Documentation
event::EventHeader::EventHeader () inline
Class constructor.
Definition at line 27 of file EventHeader.h.
 {;}
virtual event::EventHeader::~EventHeader () inline virtual
Class destructor.
Definition at line 32 of file EventHeader.h.
 {;}
Member Function Documentation
event::EventHeader::ClassDef (EventHeader , 1) protected
ROOT class definition.
void event::EventHeader::Clear (Option_t * = "") inline
Clear information from this object.
Definition at line 37 of file EventHeader.h.
References eventNumber_, isRealData_, run_, timestamp_, and weight_.
{
             eventNumber_ = -1;
             run_ = -1;
             timestamp_ = TTimeStamp(0, 0);
             weight_ = 1.0;
             isRealData_ = false;
         }
void event::EventHeader::Copy (TObject & o) const inline
Copy this object.
Parameters
o The target object.
Definition at line 62 of file EventHeader.h.
{
             ((EventHeader&) o) = *this;
         }
int event::EventHeader::getEventNumber () const inline
Return the event number.
Returns
The event number.
Definition at line 70 of file EventHeader.h.
References eventNumber_.
Referenced by ldmxsw::Process::run().
{
             return eventNumber_;
         }
int event::EventHeader::getRun () const inline
Return the run number.
Returns
The run number.
Definition at line 78 of file EventHeader.h.
References run_.
Referenced by ldmxsw::Process::run().
{
             return run_;
         }
const TTimeStamp& event::EventHeader::getTimestamp () const inline
Get the event's timestamp. This currently returns second's since the epoch for simulated events.
Returns
The event's timestamp.
Note
The returned object has a possible resolution of nanoseconds.
Definition at line 88 of file EventHeader.h.
References timestamp_.
{
             return timestamp_;
         }
double event::EventHeader::getWeight () const inline
Get the event weight (default of 1.0).
Returns
The event weight.
Definition at line 96 of file EventHeader.h.
References weight_.
{
             return weight_;
         }
bool event::EventHeader::isRealData () const inline
Is this a real data event?
Returns
True if this is a real data event.
Definition at line 104 of file EventHeader.h.
References isRealData_.
{
             return isRealData_;
         }
void event::EventHeader::Print (Option_t * = "") const inline
Print this object.
Definition at line 48 of file EventHeader.h.
References eventNumber_, isRealData_, run_, timestamp_, and weight_.
Referenced by ldmxsw::Process::run(), and sim::RootPersistencyManager::writeHeader().
{
             std::cout << "EventHeader {" << " eventNumber: " << eventNumber_ << ", run: "
                     << run_ << ", timestamp: " << timestamp_ << ", weight: " << weight_;
             if (isRealData_)
                 std::cout << ", DATA";
             else
                 std::cout << ", MC";
             std::cout << " }" << std::endl;
         }
void event::EventHeader::setEventNumber (int eventNumber) inline
Set the event number.
Parameters
eventNumber The event number.
Definition at line 112 of file EventHeader.h.
References eventNumber_.
Referenced by ldmxsw::Process::run(), and sim::RootPersistencyManager::writeHeader().
{
             this->eventNumber_ = eventNumber;
         }
void event::EventHeader::setRun (int run) inline
Set the run number.
Parameters
run The run number.
Definition at line 120 of file EventHeader.h.
References run_.
Referenced by ldmxsw::Process::run(), and sim::RootPersistencyManager::writeHeader().
{
             this->run_ = run;
         }
void event::EventHeader::setTimestamp (const TTimeStamp & timestamp) inline
Set the timestamp.
Parameters
timestamp The timestamp.
Definition at line 128 of file EventHeader.h.
References timestamp_.
Referenced by ldmxsw::Process::run(), and sim::RootPersistencyManager::writeHeader().
{
             this->timestamp_ = timestamp;
         }
void event::EventHeader::setWeight (double weight) inline
Set the event weight.
Parameters
weight The event weight.
Definition at line 136 of file EventHeader.h.
References weight_.
Referenced by sim::RootPersistencyManager::writeHeader().
{
             this->weight_ = weight;
         }
Member Data Documentation
int event::EventHeader::eventNumber_ {-1} protected
The event number.
Definition at line 145 of file EventHeader.h.
Referenced by Clear(), getEventNumber(), Print(), and setEventNumber().
bool event::EventHeader::isRealData_ {false} protected
Is this event real data?
Definition at line 165 of file EventHeader.h.
Referenced by Clear(), isRealData(), and Print().
int event::EventHeader::run_ {-1} protected
The run number.
Definition at line 150 of file EventHeader.h.
Referenced by Clear(), getRun(), Print(), and setRun().
TTimeStamp event::EventHeader::timestamp_ {0, 0} protected
The event timestamp
Definition at line 155 of file EventHeader.h.
Referenced by Clear(), getTimestamp(), Print(), and setTimestamp().
double event::EventHeader::weight_ {1.0} protected
The event weight.
Definition at line 160 of file EventHeader.h.
Referenced by Clear(), getWeight(), Print(), and setWeight().
The documentation for this class was generated from the following file:
Event/include/Event/EventHeader.h