LDMX Software: sim::SimParticleBuilder Class Reference
sim::SimParticleBuilder Class Reference
Builds output SimParticle collection from Trajectory container.
#include <SimParticleBuilder.h>
Public Types
typedef std::map< G4int,
SimParticle * > SimParticleMap
Public Member Functions
SimParticleBuilder ()
virtual ~SimParticleBuilder ()
void setCurrentEvent (const G4Event *anEvent)
void buildSimParticles (event::Event *outputEvent)
SimParticle * findSimParticle (G4int trackID)
Private Member Functions
void buildSimParticle (Trajectory *info)
void buildParticleMap (TrajectoryContainer *trajectories, TClonesArray *simParticleColl)
Private Attributes
SimParticleMap particleMap_
TrackMap * trackMap_
G4Event * currentEvent_
TClonesArray * outputParticleColl_ {new TClonesArray("event::SimParticle", 50)}
Detailed Description
Builds output SimParticle collection from Trajectory container.
Definition at line 31 of file SimParticleBuilder.h.
Member Typedef Documentation
typedef std::map<G4int, SimParticle*> sim::SimParticleBuilder::SimParticleMap
Map of track ID to SimParticles.
Definition at line 38 of file SimParticleBuilder.h.
Constructor & Destructor Documentation
sim::SimParticleBuilder::SimParticleBuilder ()
Class constructor.
Definition at line 21 of file SimParticleBuilder.cxx.
References sim::TrackMap::getInstance(), and trackMap_.
                                        : currentEvent_(nullptr) {
     trackMap_ = TrackMap::getInstance();
     outputParticleColl_ = new TClonesArray("event::SimParticle", 50);
 }
sim::SimParticleBuilder::~SimParticleBuilder () virtual
Class destructor.
Definition at line 26 of file SimParticleBuilder.cxx.
{
     delete outputParticleColl_;
 }
Member Function Documentation
void sim::SimParticleBuilder::buildParticleMap (TrajectoryContainer * trajectories, TClonesArray * simParticleColl) private
Build the SimParticle map from the trajectory container. This will create SimParticles without their information filled.
Parameters
trajectories The input trajectory container.
simParticleColl The output SimParticle collection.
Definition at line 96 of file SimParticleBuilder.cxx.
References particleMap_.
Referenced by buildSimParticles().
{
     particleMap_.clear();
     for (auto trajectory : *trajectories->GetVector()) {
         particleMap_[trajectory->GetTrackID()]
             = (SimParticle*) simParticleColl->ConstructedAt(simParticleColl->GetEntries());
     }
 }
void sim::SimParticleBuilder::buildSimParticle (Trajectory * info) private
Build a SimParticle from trajectory information.
Parameters
info The trajectory information.
Definition at line 53 of file SimParticleBuilder.cxx.
References event::SimParticle::addDaughter(), event::SimParticle::addParent(), findSimParticle(), sim::Trajectory::GetCharge(), sim::Trajectory::getEnergy(), sim::Trajectory::getGenStatus(), sim::Trajectory::getGlobalTime(), sim::Trajectory::GetInitialMomentum(), sim::Trajectory::getMass(), sim::Trajectory::GetParentID(), sim::Trajectory::GetPDGEncoding(), sim::Trajectory::GetPoint(), sim::Trajectory::GetPointEntries(), sim::Trajectory::GetTrackID(), sim::Trajectory::getVertexPosition(), particleMap_, event::SimParticle::setCharge(), event::SimParticle::setEndPoint(), event::SimParticle::setEnergy(), event::SimParticle::setGenStatus(), event::SimParticle::setMass(), event::SimParticle::setMomentum(), event::SimParticle::setPdgID(), event::SimParticle::setTime(), and event::SimParticle::setVertex().
Referenced by buildSimParticles().
{
     SimParticle* simParticle = particleMap_[traj->GetTrackID()];
     if (!simParticle) {
         std::cerr << "[ SimParticleBuilder ] : SimParticle not found for Trajectory with track ID "
                 << traj->GetTrackID() << std::endl;
         G4Exception("SimParticleBuilder::buildSimParticle",
                 "",
                 FatalException,
                 "SimParticle not found for Trajectory.");
     }
     simParticle->setGenStatus(traj->getGenStatus());
     simParticle->setPdgID(traj->GetPDGEncoding());
     simParticle->setCharge(traj->GetCharge());
     simParticle->setMass(traj->getMass());
     simParticle->setEnergy(traj->getEnergy());
     G4ThreeVector lastTrajPoint = traj->GetPoint(traj->GetPointEntries() - 1)->GetPosition();
     simParticle->setEndPoint(lastTrajPoint[0], lastTrajPoint[1], lastTrajPoint[2]);
     const G4ThreeVector& momentum = traj->GetInitialMomentum();
     simParticle->setMomentum(momentum[0], momentum[1], momentum[2]);
     const G4ThreeVector& vertex = traj->getVertexPosition();
     simParticle->setVertex(vertex[0], vertex[1], vertex[2]);
     simParticle->setTime(traj->getGlobalTime());
     if (traj->GetParentID() > 0) {
         SimParticle* parent = findSimParticle(traj->GetParentID());
         if (parent != NULL) {
             simParticle->addParent(parent);
             parent->addDaughter(simParticle);
         } else {
             std::cerr << "[ SimParticleBuilder ] - WARNING: SimParticle with parent ID "
                       << traj->GetParentID() << " not found for track ID "
                       << traj->GetTrackID() << std::endl;
         }
     }
 }
void sim::SimParticleBuilder::buildSimParticles (event::Event * outputEvent)
Build SimParticle collection into an output event.
Parameters
outputEvent The output event.
Definition at line 30 of file SimParticleBuilder.cxx.
References event::Event::add(), buildParticleMap(), buildSimParticle(), and currentEvent_.
Referenced by sim::RootPersistencyManager::buildEvent().
{
     // Clear the output particle collection.
     outputParticleColl_->Clear("C");
     // Get the trajectory container for the event.
     TrajectoryContainer* trajectories
         = (TrajectoryContainer*)(const_cast<G4Event*>(currentEvent_))->GetTrajectoryContainer();
     // Create empty SimParticle objects and create the map of track ID to particles.
     buildParticleMap(trajectories, outputParticleColl_);
     // Fill information into the particles.
     for (auto trajectory : *trajectories->GetVector()) {
         buildSimParticle(static_cast<Trajectory*>(trajectory));
     }
     // Add the collection data to the output event.
     outputEvent->add("SimParticles", outputParticleColl_);
     std::cout << "[ SimParticleBuilder ] : Wrote " << outputParticleColl_->GetEntriesFast() << " SimParticle objects" << std::endl;
 }
SimParticle * sim::SimParticleBuilder::findSimParticle (G4int trackID)
Find a SimParticle by track ID.
Parameters
trackID The trackID of the particle.
Definition at line 104 of file SimParticleBuilder.cxx.
References currentEvent_, sim::TrackMap::findTrajectory(), particleMap_, and trackMap_.
Referenced by buildSimParticle(), sim::RootPersistencyManager::writeCalorimeterHitsCollection(), sim::EcalHitIO::writeHitsCollection(), and sim::RootPersistencyManager::writeTrackerHitsCollection().
{
     G4VTrajectory* traj = trackMap_->findTrajectory(currentEvent_, trackID);
     if (traj != NULL) {
         return particleMap_[traj->GetTrackID()];
     } else {
         return NULL;
     }
 }
void sim::SimParticleBuilder::setCurrentEvent (const G4Event * anEvent) inline
Set the current Geant4 event.
Parameters
anEvent The Geant4 event.
Definition at line 54 of file SimParticleBuilder.h.
References currentEvent_.
Referenced by sim::RootPersistencyManager::buildEvent().
{
             this->currentEvent_ = const_cast<G4Event*>(anEvent);
         }
Member Data Documentation
G4Event* sim::SimParticleBuilder::currentEvent_ private
The current Geant4 event.
Definition at line 101 of file SimParticleBuilder.h.
Referenced by buildSimParticles(), findSimParticle(), and setCurrentEvent().
SimParticleMap sim::SimParticleBuilder::particleMap_ private
The map of track IDs to SimParticles.
Definition at line 91 of file SimParticleBuilder.h.
Referenced by buildParticleMap(), buildSimParticle(), and findSimParticle().
TrackMap* sim::SimParticleBuilder::trackMap_ private
The map of track ancestry (track ID to parent ID).
Definition at line 96 of file SimParticleBuilder.h.
Referenced by findSimParticle(), and SimParticleBuilder().
The documentation for this class was generated from the following files:
SimApplication/include/SimApplication/SimParticleBuilder.h
SimApplication/src/SimParticleBuilder.cxx