LDMX Software: event::Event Class Reference
event::Event Class Reference abstract
Defines an interface for accessing event data.
#include <Event.h>
Public Member Functions
Event ()
virtual ~Event ()
virtual const EventHeader * getEventHeader () const =0
bool exists (const std::string &name)
bool exists (const std::string &name, const std::string &passName)
template<typename ObjectType >
const ObjectType get (const std::string &name)
template<typename ObjectType >
const ObjectType get (const std::string &name, const std::string &passName)
const TClonesArray * getCollection (const std::string &collectionName)
const TClonesArray * getCollection (const std::string &collectionName, std::string passName)
virtual void add (const std::string &collectionName, TClonesArray *clones)=0
virtual void add (const std::string &name, TObject *obj)=0
virtual void addToCollection (const std::string &name, const TObject &obj)=0
Protected Member Functions
virtual const TObject * getReal (const std::string &itemName, const std::string &passName, bool mustExist)=0
Detailed Description
Defines an interface for accessing event data.
Note
A backing EventImpl object provides the actual data collections via ROOT data structures (trees and branches).
Definition at line 31 of file Event.h.
Constructor & Destructor Documentation
event::Event::Event () inline
Class constructor.
Definition at line 38 of file Event.h.
 {;}
virtual event::Event::~Event () inline virtual
Class destructor.
Definition at line 43 of file Event.h.
 {;}
Member Function Documentation
virtual void event::Event::add (const std::string & collectionName, TClonesArray * clones) pure virtual
Add a collection (TClonesArray) of objects to the event. The current pass name will be used for the collection.
Parameters
collectionName The name of the collection.
clones The TClonesArray containing the objects.
Implemented in ldmxsw::EventImpl.
Referenced by sim::SimParticleBuilder::buildSimParticles(), and sim::RootPersistencyManager::writeHitsCollections().
virtual void event::Event::add (const std::string & name, TObject * obj) pure virtual
Add an object to the event. The current pass name will be used for the object.
Parameters
collectionName The name of the collection.
clones The TClonesArray containing the objects.
Implemented in ldmxsw::EventImpl.
virtual void event::Event::addToCollection (const std::string & name, const TObject & obj) pure virtual
Add the given object to the named TClonesArray collection Objects can only be added to a TClonesArray during the current pass – TClonesArrays loaded from the input data file are not allowed to be changed.
Note
Object types must implement TObject::Copy().
Parameters
name Name of the collection.
obj Object to be appended to the collection.
Implemented in ldmxsw::EventImpl.
bool event::Event::exists (const std::string & name) inline
Check the existence of one-and-only-one object with the given name (excluding the pass) in the event.
Parameters
name Name (label, not class name) given to the object when it was put into the event.
Returns
True if the object or collection exists in the event.
Definition at line 57 of file Event.h.
References getReal().
{
             return getReal(name, "", false) != 0;
         }
bool event::Event::exists (const std::string & name, const std::string & passName) inline
Check for the existence of an object or collection with the given name and pass name in the event.
Parameters
name Name (label, not class name) given to the object when it was put into the event.
passName The process pass label which was in use when this object was put into the event, such as "sim" or "rerecov2".
Returns
True if the object or collection exists in the event.
Definition at line 68 of file Event.h.
References getReal().
{
             return getReal(name, passName, false) != 0;
         }
template<typename ObjectType > const ObjectType event::Event::get (const std::string & name) inline
Get a named object with a specific type without specifying the pass name. If there is one-and-only-one object with the given name (excluding the pass) in the event, it will be returned, otherwise an exception will be thrown.
Parameters
name Name (label, not classname) given to the object when it was put into the event.
Returns
A named object from the event.
Definition at line 80 of file Event.h.
References getReal().
Referenced by sim::RootPersistencyManager::printEvent().
{
             return (ObjectType) getReal(name, "", true);
         }
template<typename ObjectType > const ObjectType event::Event::get (const std::string & name, const std::string & passName) inline
Get a named object with a specific type, specifying the pass name. If there is no object which matches, an exception will be thrown.
Parameters
name Name (label, not classname) given to the object when it was put into the event.
passName The process pass label which was in use when this object was put into the event, such as "sim" or "rerecov2".
Returns
A named object from the event.
Definition at line 92 of file Event.h.
References getReal().
{
             return (ObjectType) getReal(name, passName, true);
         }
const TClonesArray* event::Event::getCollection (const std::string & collectionName) inline
Get a collection (TClonesArray) from the event without specifying the pass name. If there is one-and-only-one object with the given name (excluding the pass) in the event, it will be returned, otherwise an exception will be thrown.
Parameters
name Name (label, not class name) given to the object when it was put into the event.
Returns
The named TClonesArray from the event.
Definition at line 104 of file Event.h.
References getReal().
Referenced by HcalDigiProducer::produce(), and EcalDigiProducer::produce().
{
             return (TClonesArray*) getReal(collectionName, "", true);
         }
const TClonesArray* event::Event::getCollection (const std::string & collectionName, std::string passName) inline
Get an object collection (TClonesArray) from the event, specifying the pass name. If there is no object which matches, an exception will be thrown.
Parameters
collectionName Name given to the collection when it was put into the event.
passName The process pass label which was in use when this object was put into the event, such as "sim" or "rerecov2".
Returns
A named TClonesArray from the event.
Definition at line 116 of file Event.h.
References getReal().
{
             return (TClonesArray*) getReal(collectionName, passName, true);
         }
virtual const EventHeader* event::Event::getEventHeader () const pure virtual
Get the event header.
Returns
The event header.
Implemented in ldmxsw::EventImpl.
virtual const TObject* event::Event::getReal (const std::string & itemName, const std::string & passName, bool mustExist) protected pure virtual
Actual get implementation, provided by derived class.
Parameters
itemName The name of the object or TClonesArray.
passName The process pass label which was in use when this object was put into the event.
mustExist Determines if an exception should be thrown if the object does not exist – used by exists() methods.
clones The TClonesArray containing the objects.
Implemented in ldmxsw::EventImpl.
Referenced by exists(), get(), and getCollection().
The documentation for this class was generated from the following file:
Event/include/Event/Event.h