LDMX Software: sim::MagneticFieldStore Class Reference
sim::MagneticFieldStore Class Reference
Global store to access magnetic field objects.
#include <MagneticFieldStore.h>
Public Types
typedef std::map< std::string,
G4MagneticField * > MagFieldMap
Public Member Functions
G4MagneticField * getMagneticField (const std::string &name)
void addMagneticField (const std::string &name, G4MagneticField *magField)
Static Public Member Functions
static MagneticFieldStore * getInstance ()
Private Attributes
MagFieldMap magFields_
Detailed Description
Global store to access magnetic field objects.
Definition at line 19 of file MagneticFieldStore.h.
Member Typedef Documentation
typedef std::map<std::string, G4MagneticField*> sim::MagneticFieldStore::MagFieldMap
Map of names to magnetic fields.
Definition at line 26 of file MagneticFieldStore.h.
Member Function Documentation
void sim::MagneticFieldStore::addMagneticField (const std::string & name, G4MagneticField * magField) inline
Add a magnetic field by name.
Parameters
name The name of the magnetic field.
magField The magnetic field definition.
Definition at line 50 of file MagneticFieldStore.h.
References magFields_.
Referenced by sim::AuxInfoReader::createMagneticField().
{
             magFields_[name] = magField;
         }
static MagneticFieldStore* sim::MagneticFieldStore::getInstance () inline static
Get the global instance of the magnetic field store.
Returns
The magnetic field store.
Definition at line 32 of file MagneticFieldStore.h.
Referenced by sim::AuxInfoReader::assignAuxInfoToVolumes(), and sim::AuxInfoReader::createMagneticField().
{
             static MagneticFieldStore INSTANCE;
             return &INSTANCE;
         }
G4MagneticField* sim::MagneticFieldStore::getMagneticField (const std::string & name) inline
Get a magnetic field by name.
Parameters
name The name of the magnetic field.
Definition at line 41 of file MagneticFieldStore.h.
References magFields_.
Referenced by sim::AuxInfoReader::assignAuxInfoToVolumes().
{
             return magFields_[name];
         }
Member Data Documentation
MagFieldMap sim::MagneticFieldStore::magFields_ private
Map of names to magnetic fields.
Definition at line 59 of file MagneticFieldStore.h.
Referenced by addMagneticField(), and getMagneticField().
The documentation for this class was generated from the following file:
SimApplication/include/SimApplication/MagneticFieldStore.h