LDMX Software: ldmxsw::EventFile Class Reference
ldmxsw::EventFile Class Reference
Manages a file of events.
#include <EventFile.h>
Public Member Functions
EventFile (const std::string &fileName, std::string treeName, bool isOutputFile=false, int compressionLevel=9)
EventFile (const std::string &fileName, bool isOutputFile=false, int compressionLevel=9)
EventFile (const std::string &fileName, EventFile *cloneParent, int compressionLevel=9)
void addDrop (const std::string &rule)
void setupEvent (EventImpl *evt)
EventImpl * getEvent ()
bool nextEvent ()
void close ()
Private Attributes
Long64_t entries_ {-1}
Long64_t ientry_ {-1}
std::string fileName_
bool isOutputFile_
TFile * file_ {nullptr}
TTree * tree_ {nullptr}
EventFile * parent_ {nullptr}
EventImpl * event_ {nullptr}
Detailed Description
Manages a file of events.
Definition at line 27 of file EventFile.h.
Constructor & Destructor Documentation
ldmxsw::EventFile::EventFile (const std::string & fileName, std::string treeName, bool isOutputFile = false, int compressionLevel = 9)
Class constructor to make a file with a custom tree name.
Parameters
fileName The file name.
treeName The name of the tree containing event data.
isOutputFile True if this file is written out.
compressionLevel The compression level.
Definition at line 8 of file EventFile.cxx.
References entries_, EXCEPTION_RAISE, file_, isOutputFile_, and tree_.
                                                                                                            :
         fileName_(filename), isOutputFile_(isOutputFile) {
     if (isOutputFile_) {
         file_ = new TFile(filename.c_str(), "RECREATE");
         if (!file_->IsWritable()) {
             EXCEPTION_RAISE("FileError", "Output file '" + filename + "' is not writable");
         }
     } else {
         file_ = new TFile(filename.c_str());
     }
     if (!file_->IsOpen()) {
         EXCEPTION_RAISE("FileError", "File '" + filename + "' is not readable or does not exist.");
     }
     if (isOutputFile_) {
         file_->SetCompressionLevel(compressionLevel);
     }
     if (!isOutputFile_) {
         tree_ = (TTree*) (file_->Get(treeName.c_str()));
         entries_ = tree_->GetEntriesFast();
     }
 }
ldmxsw::EventFile::EventFile (const std::string & fileName, bool isOutputFile = false, int compressionLevel = 9)
Class constructor to make a file with the default tree name.
Parameters
fileName The file name.
isOutputFile True if this file is written out.
compressionLevel The compression level.
Definition at line 35 of file EventFile.cxx.
                                                                                        :
         EventFile(filename, event::EventConstants::EVENT_TREE_NAME, isOutputFile, compressionLevel) {
 }
ldmxsw::EventFile::EventFile (const std::string & fileName, EventFile * cloneParent, int compressionLevel = 9)
Class constructor for cloning data from a "parent" file.
Parameters
fileName The file name.
cloneParent Parent file for cloning data tree.
compressionLevel The compression level.
Definition at line 39 of file EventFile.cxx.
References EXCEPTION_RAISE, file_, isOutputFile_, parent_, and tree_.
                                                                                             :
         fileName_(filename), isOutputFile_(true), parent_(cloneParent) {
     file_ = new TFile(filename.c_str(), "RECREATE");
     if (!file_->IsWritable()) {
         EXCEPTION_RAISE("FileError", "Output file '" + filename + "' is not writable");
     }
     if (!file_->IsOpen()) {
         EXCEPTION_RAISE("FileError", "File '" + filename + "' is not readable or does not exist.");
     }
     parent_->tree_->SetBranchStatus("*", 1);
     if (isOutputFile_) {
         file_->SetCompressionLevel(compressionLevel);
     }
 }
Member Function Documentation
void ldmxsw::EventFile::addDrop (const std::string & rule)
Add a rule for dropping collections from the output.
Parameters
rule The rule for dropping collections.
Todo:
Need to document the string format.
Need to verify that dropping objects works.
Definition at line 59 of file EventFile.cxx.
References parent_, and tree_.
Referenced by ldmxsw::Process::run().
{
     if (parent_ == 0)
         return;
     size_t i = rule.find("keep");
     bool iskeep = i != std::string::npos;
     if (!iskeep)
         i = rule.find("drop");
     if (i == std::string::npos)
         return;
     std::string srule = rule.substr(i + 4);
     for (i = srule.find_first_of(" \t\n\r"); i != std::string::npos; i = srule.find_first_of(" \t\n\r"))
         srule.erase(i, 1);
     if (srule.length() == 0)
         return;
     if (srule.back() != '*')
         srule += '*';
     parent_->tree_->SetBranchStatus(srule.c_str(), (iskeep) ? (1) : (0));
 }
void ldmxsw::EventFile::close ()
Close the file, writing the tree to disk if creating an output file.
Definition at line 162 of file EventFile.cxx.
References file_, isOutputFile_, and tree_.
Referenced by ldmxsw::Process::run(), and sim::RootPersistencyManager::Store().
                       {
     if (isOutputFile_)
         tree_->Write();
     file_->Close();
 }
EventImpl* ldmxsw::EventFile::getEvent () inline
Get the EventImpl object containing the event data.
Returns
The EventImpl object containing event data.
Definition at line 75 of file EventFile.h.
References event_.
 { return event_; };
bool ldmxsw::EventFile::nextEvent ()
Prepare the next event.
Returns
If event was prepared/read successfully.
Definition at line 85 of file EventFile.cxx.
References ldmxsw::EventImpl::beforeFill(), ldmxsw::EventImpl::Clear(), entries_, event_, EXCEPTION_RAISE, ientry_, isOutputFile_, nextEvent(), ldmxsw::EventImpl::nextEvent(), ldmxsw::EventImpl::onEndOfEvent(), parent_, ldmxsw::EventImpl::setInputTree(), ldmxsw::EventImpl::setOutputTree(), and tree_.
Referenced by nextEvent(), ldmxsw::Process::run(), and sim::RootPersistencyManager::Store().
{
     if (ientry_ < 0 && parent_) {
         if (!parent_->tree_) {
             EXCEPTION_RAISE("EventFile", "No event tree in the file");
         }
         tree_ = parent_->tree_->CloneTree(0);
         event_->setInputTree(parent_->tree_);
         event_->setOutputTree(tree_);
     }
     // close up the last event
     if (ientry_ >= 0) {
         if (isOutputFile_) {
             event_->beforeFill();
             tree_->Fill(); // fill the clones...
             event_->Clear();
         }
         if (event_) {
             event_->onEndOfEvent();
         }
     }
     if (parent_) {
         if (!parent_->nextEvent()) {
             return false;
         }
         parent_->tree_->GetEntry(parent_->ientry_);
         ientry_ = parent_->ientry_;
         event_->nextEvent();
         entries_++;
         return true;
     } else {
         // if we are reading, move the pointer
         if (!isOutputFile_) {
             if (ientry_ + 1 >= entries_) {
                 return false;
             }
             ientry_++;
             tree_->LoadTree(ientry_);
             if (event_) {
                 event_->nextEvent();
             }
             return true;
         } else {
             ientry_++;
             entries_++;
             return true;
         }
     }
     return false;
 }
void ldmxsw::EventFile::setupEvent (EventImpl * evt)
Set an EventImpl object containing the event data to work with this file.
Parameters
evt The EventImpl object with event data.
Definition at line 144 of file EventFile.cxx.
References ldmxsw::EventImpl::createTree(), entries_, event_, ientry_, isOutputFile_, parent_, ldmxsw::EventImpl::setInputTree(), and tree_.
Referenced by sim::RootPersistencyManager::Initialize(), and ldmxsw::Process::run().
{
     event_ = evt;
     if (isOutputFile_) {
         if (!tree_ && !parent_) {
             tree_ = event_->createTree();
             ientry_ = 0;
             entries_ = 0;
         }
         if (parent_) {
             event_->setInputTree(parent_->tree_);
         }
     } else {
         event_->setInputTree(tree_);
     }
 }
Member Data Documentation
Long64_t ldmxsw::EventFile::entries_ {-1} private
The number of entries in the tree.
Definition at line 91 of file EventFile.h.
Referenced by EventFile(), nextEvent(), and setupEvent().
EventImpl* ldmxsw::EventFile::event_ {nullptr} private
The object containing the actual event data (trees and branches).
Definition at line 112 of file EventFile.h.
Referenced by getEvent(), nextEvent(), and setupEvent().
TFile* ldmxsw::EventFile::file_ {nullptr} private
The backing TFile for this EventFile.
Definition at line 103 of file EventFile.h.
Referenced by close(), and EventFile().
std::string ldmxsw::EventFile::fileName_ private
The file name.
Definition at line 97 of file EventFile.h.
Long64_t ldmxsw::EventFile::ientry_ {-1} private
The current entry in the tree.
Definition at line 94 of file EventFile.h.
Referenced by nextEvent(), and setupEvent().
bool ldmxsw::EventFile::isOutputFile_ private
True if file is an output file being written to disk.
Definition at line 100 of file EventFile.h.
Referenced by close(), EventFile(), nextEvent(), and setupEvent().
EventFile* ldmxsw::EventFile::parent_ {nullptr} private
A parent file containing event data.
Definition at line 109 of file EventFile.h.
Referenced by addDrop(), EventFile(), nextEvent(), and setupEvent().
TTree* ldmxsw::EventFile::tree_ {nullptr} private
The tree with event data.
Definition at line 106 of file EventFile.h.
Referenced by addDrop(), close(), EventFile(), nextEvent(), and setupEvent().
The documentation for this class was generated from the following files:
Framework/include/Framework/EventFile.h
Framework/src/EventFile.cxx