LDMX Software: sim::TrackMap Class Reference
sim::TrackMap Class Reference
Defines a map of track ID to parent ID.
#include <TrackMap.h>
Public Types
typedef std::map< G4int, G4int > TrackIDMap
Public Member Functions
void addSecondary (G4int trackID, G4int parentID)
G4VTrajectory * findTrajectory (const G4Event *anEvent, G4int trackID)
void clear ()
Static Public Member Functions
static TrackMap * getInstance ()
Private Attributes
TrackIDMap trackIDMap_
Detailed Description
Defines a map of track ID to parent ID.
Note
This class provides a record of track ancestry which is used to connect track IDs to their parents.
Definition at line 24 of file TrackMap.h.
Member Typedef Documentation
typedef std::map<G4int, G4int> sim::TrackMap::TrackIDMap
Map of track ID to parent ID.
Definition at line 31 of file TrackMap.h.
Member Function Documentation
void sim::TrackMap::addSecondary (G4int trackID, G4int parentID)
Add a record in the map connecting a track ID to its parent ID.
Parameters
trackID The track ID.
parentID The parent track ID.
Definition at line 17 of file TrackMap.cxx.
References trackIDMap_.
Referenced by sim::UserTrackingAction::PreUserTrackingAction().
{
     trackIDMap_[trackID] = parentID;
 }
void sim::TrackMap::clear ()
Clear the map.
Definition at line 40 of file TrackMap.cxx.
References trackIDMap_.
Referenced by sim::UserEventAction::BeginOfEventAction().
                      {
     trackIDMap_.clear();
 }
G4VTrajectory * sim::TrackMap::findTrajectory (const G4Event * anEvent, G4int trackID)
Find a trajectory by its track ID in the event.
Parameters
anEvent The Geant4 event.
trackkID The track ID of the trajectory to find.
Definition at line 21 of file TrackMap.cxx.
References sim::TrajectoryContainer::findByTrackID(), and trackIDMap_.
Referenced by sim::SimParticleBuilder::findSimParticle().
{
     TrajectoryContainer* trajectories = (TrajectoryContainer*)anEvent->GetTrajectoryContainer();
     G4int currTrackID = trackID;
     G4VTrajectory* traj = NULL;
     for (;;) {
         traj = trajectories->findByTrackID(currTrackID);
         if (traj != NULL) {
             break;
         } else {
             if (trackIDMap_.find(currTrackID) != trackIDMap_.end()) {
                 currTrackID = trackIDMap_[currTrackID];
             } else {
                 break;
             }
         }
     }
     return traj;
 }
TrackMap * sim::TrackMap::getInstance () static
Get the global instance of the map.
Returns
The global instance of the map.
Definition at line 12 of file TrackMap.cxx.
Referenced by sim::UserEventAction::BeginOfEventAction(), sim::UserTrackingAction::PreUserTrackingAction(), and sim::SimParticleBuilder::SimParticleBuilder().
{
     static TrackMap INSTANCE;
     return &INSTANCE;
 }
Member Data Documentation
TrackIDMap sim::TrackMap::trackIDMap_ private
The map of track IDs to parent IDs.
Definition at line 63 of file TrackMap.h.
Referenced by addSecondary(), clear(), and findTrajectory().
The documentation for this class was generated from the following files:
SimApplication/include/SimApplication/TrackMap.h
SimApplication/src/TrackMap.cxx