LDMX Software: sim::DetectorConstruction Class Reference
sim::DetectorConstruction Class Reference
Implements the Geant4 detector construction.
#include <DetectorConstruction.h>
Public Member Functions
DetectorConstruction (G4GDMLParser *theParser)
virtual ~DetectorConstruction ()
G4VPhysicalVolume * Construct ()
detdescr::DetectorHeader * getDetectorHeader ()
Private Attributes
G4GDMLParser * parser_
AuxInfoReader * auxInfoReader_
Detailed Description
Implements the Geant4 detector construction.
Note
This class reads in a detector description from a GDML file using the basic G4GDMLParser and instantiates supplemental information using the AuxInfoReader.
See Also
AuxInfoReader
Definition at line 30 of file DetectorConstruction.h.
Constructor & Destructor Documentation
sim::DetectorConstruction::DetectorConstruction (G4GDMLParser * theParser)
Class constructor.
Parameters
theParser GDML parser defining the geometry.
Definition at line 5 of file DetectorConstruction.cxx.
                                                                   :
     parser_(theParser),
     auxInfoReader_(new AuxInfoReader(theParser)) {
 }
sim::DetectorConstruction::~DetectorConstruction () virtual
Class destructor.
Definition at line 10 of file DetectorConstruction.cxx.
References auxInfoReader_.
{
     delete auxInfoReader_;
 }
Member Function Documentation
G4VPhysicalVolume * sim::DetectorConstruction::Construct ()
Construct the detector.
Returns
The top volume of the detector.
Definition at line 14 of file DetectorConstruction.cxx.
References sim::AuxInfoReader::assignAuxInfoToVolumes(), auxInfoReader_, parser_, and sim::AuxInfoReader::readGlobalAuxInfo().
{
     auxInfoReader_->readGlobalAuxInfo();
     auxInfoReader_->assignAuxInfoToVolumes();
     return parser_->GetWorldVolume();
 }
detdescr::DetectorHeader* sim::DetectorConstruction::getDetectorHeader () inline
Get the detector header.
Returns
The detector header.
Definition at line 55 of file DetectorConstruction.h.
References auxInfoReader_, and sim::AuxInfoReader::getDetectorHeader().
Referenced by sim::RootPersistencyManager::createRunHeader().
{
             return auxInfoReader_->getDetectorHeader();
         }
Member Data Documentation
AuxInfoReader* sim::DetectorConstruction::auxInfoReader_ private
The auxiliary GDML info reader.
Definition at line 69 of file DetectorConstruction.h.
Referenced by Construct(), getDetectorHeader(), and ~DetectorConstruction().
G4GDMLParser* sim::DetectorConstruction::parser_ private
The GDML parser defining the detector.
Definition at line 64 of file DetectorConstruction.h.
Referenced by Construct().
The documentation for this class was generated from the following files:
SimApplication/include/SimApplication/DetectorConstruction.h
SimApplication/src/DetectorConstruction.cxx