LDMX Software: sim::Trajectory Class Reference
sim::Trajectory Class Reference
Trajectory implementation for storing track info for persistence and visualization.
#include <Trajectory.h>
Public Member Functions
Trajectory (const G4Track *aTrack)
virtual ~Trajectory ()
void * operator new (size_t s)
void operator delete (void *obj)
G4int GetTrackID () const
G4int GetParentID () const
G4String GetParticleName () const
G4double GetCharge () const
G4int GetPDGEncoding () const
G4ThreeVector GetInitialMomentum () const
int GetPointEntries () const
G4VTrajectoryPoint * GetPoint (G4int i) const
void AppendStep (const G4Step *aStep)
void MergeTrajectory (G4VTrajectory *secondTrajectory)
const G4ThreeVector & getEndPoint () const
G4double getEnergy () const
G4double getMass () const
G4float getGlobalTime () const
G4int getGenStatus () const
const G4ThreeVector & getVertexPosition () const
void setGenStatus (int genStatus)
Private Attributes
TrajectoryPointContainer * trajPoints_
G4ParticleDefinition * particleDef_
G4int trackID_
G4int parentID_
G4double energy_
G4double mass_
G4float globalTime_
G4int genStatus_
G4ThreeVector initialMomentum_
G4ThreeVector vertexPosition_
G4ThreeVector endPoint_
Detailed Description
Trajectory implementation for storing track info for persistence and visualization.
Note
Class is based on this Geant4 tip: Trajectory Event Tip
Definition at line 30 of file Trajectory.h.
Constructor & Destructor Documentation
sim::Trajectory::Trajectory (const G4Track * aTrack)
Class constructor.
Parameters
aTrack The Track from which to construct the trajectory.
Definition at line 10 of file Trajectory.cxx.
References energy_, globalTime_, initialMomentum_, mass_, parentID_, particleDef_, trackID_, trajPoints_, and vertexPosition_.
     : genStatus_(0) {
     particleDef_ = aTrack->GetDefinition();
     mass_ = aTrack->GetDynamicParticle()->GetMass();
     trackID_ = aTrack->GetTrackID();
     parentID_ = aTrack->GetParentID();
     initialMomentum_ = aTrack->GetMomentum();
     energy_ = aTrack->GetTotalEnergy();
     globalTime_ = aTrack->GetGlobalTime();
     vertexPosition_ = aTrack->GetVertexPosition();
     trajPoints_ = new TrajectoryPointContainer();
     trajPoints_->push_back(new G4TrajectoryPoint(aTrack->GetPosition()));
 }
sim::Trajectory::~Trajectory () virtual
Class destructor.
Definition at line 26 of file Trajectory.cxx.
References trajPoints_.
{
     // Delete trajectory points and their container.
     size_t i;
     for(i = 0; i < trajPoints_->size(); i++) {
         delete (*trajPoints_)[i];
     }
     trajPoints_->clear();
     delete trajPoints_;
 }
Member Function Documentation
void sim::Trajectory::AppendStep (const G4Step * aStep)
Append a step to the trajectory.
Parameters
aStep The step info.
Definition at line 36 of file Trajectory.cxx.
References trajPoints_.
{
    trajPoints_->push_back(new G4TrajectoryPoint(aStep->GetPostStepPoint()->GetPosition()));
 }
G4double sim::Trajectory::GetCharge () const
Get the charge of the particle.
Returns
The charge of the particle.
Definition at line 52 of file Trajectory.cxx.
References particleDef_.
Referenced by sim::SimParticleBuilder::buildSimParticle().
{
     return particleDef_->GetPDGCharge();
 }
const G4ThreeVector & sim::Trajectory::getEndPoint () const
Get the trajectory end point [mm].
Returns
The trajectory end point.
Definition at line 86 of file Trajectory.cxx.
References endPoint_.
{
     return endPoint_;
 }
G4double sim::Trajectory::getEnergy () const
Get the particle's energy [MeV].
Returns
The trajectory's energy.
Definition at line 90 of file Trajectory.cxx.
References energy_.
Referenced by sim::SimParticleBuilder::buildSimParticle().
{
     return energy_;
 }
G4int sim::Trajectory::getGenStatus () const
Get the generator status (greater than zero for generator particle).
Returns
The particle's generator status.
Definition at line 102 of file Trajectory.cxx.
References genStatus_.
Referenced by sim::SimParticleBuilder::buildSimParticle().
{
     return genStatus_;
 }
G4float sim::Trajectory::getGlobalTime () const
Get the global creation time of the trajectory.
Definition at line 98 of file Trajectory.cxx.
References globalTime_.
Referenced by sim::SimParticleBuilder::buildSimParticle().
{
     return globalTime_;
 }
G4ThreeVector sim::Trajectory::GetInitialMomentum () const
Get the initial track momentum [MeV].
Returns
The initial track momentum.
Definition at line 60 of file Trajectory.cxx.
References initialMomentum_.
Referenced by sim::SimParticleBuilder::buildSimParticle().
{
     return initialMomentum_;
 }
G4double sim::Trajectory::getMass () const
Get the particle's mass [MeV].
Returns
The particle's mass.
Definition at line 94 of file Trajectory.cxx.
References mass_.
Referenced by sim::SimParticleBuilder::buildSimParticle().
{
     return mass_;
 }
G4int sim::Trajectory::GetParentID () const
Get the parent track ID.
Returns
The parent track ID.
Definition at line 44 of file Trajectory.cxx.
References parentID_.
Referenced by sim::SimParticleBuilder::buildSimParticle().
{
     return parentID_;
 }
G4String sim::Trajectory::GetParticleName () const
Get the name of the associated particle.
Returns
The name of the particle.
Definition at line 48 of file Trajectory.cxx.
References particleDef_.
{
     return particleDef_->GetParticleName();
 }
G4int sim::Trajectory::GetPDGEncoding () const
Get the PDG encoding of the particle.
Returns
The PDG encoding of the particle.
Definition at line 56 of file Trajectory.cxx.
References particleDef_.
Referenced by sim::SimParticleBuilder::buildSimParticle().
{
     return particleDef_->GetPDGEncoding();
 }
G4VTrajectoryPoint * sim::Trajectory::GetPoint (G4int i) const
Get a trajectory point.
Parameters
i The index of the trajectory point.
Definition at line 68 of file Trajectory.cxx.
References trajPoints_.
Referenced by sim::SimParticleBuilder::buildSimParticle().
{
     return (*trajPoints_)[i];
 }
int sim::Trajectory::GetPointEntries () const
Get the number of trajectory points.
Returns
The number of trajectory points.
Definition at line 64 of file Trajectory.cxx.
References trajPoints_.
Referenced by sim::SimParticleBuilder::buildSimParticle(), and MergeTrajectory().
{
     return trajPoints_->size();
 }
G4int sim::Trajectory::GetTrackID () const
Get the associated track ID.
Returns
The track ID.
Definition at line 40 of file Trajectory.cxx.
References trackID_.
Referenced by sim::SimParticleBuilder::buildSimParticle().
{
     return trackID_;
 }
const G4ThreeVector & sim::Trajectory::getVertexPosition () const
Get the particle's vertex position.
Returns
The particle's vertex position.
Definition at line 106 of file Trajectory.cxx.
References vertexPosition_.
Referenced by sim::SimParticleBuilder::buildSimParticle().
{
     return vertexPosition_;
 }
void sim::Trajectory::MergeTrajectory (G4VTrajectory * secondTrajectory)
Merge a trajectory into this one.
Parameters
secondTrajectory The trajectory to merge into this one.
Definition at line 72 of file Trajectory.cxx.
References GetPointEntries(), and trajPoints_.
{
     if (secondTrajectory == NULL) {
         return;
     }
     Trajectory* seco = (Trajectory*)secondTrajectory;
     G4int ent = seco->GetPointEntries();
     for(int i=1; i<ent; i++) {
         trajPoints_->push_back((*(seco->trajPoints_))[i]);
     }
     delete (*seco->trajPoints_)[0];
     seco->trajPoints_->clear();
 }
void sim::Trajectory::operator delete (void * obj) inline
Delete a trajectory.
Parameters
obj The object to delete.
Definition at line 228 of file Trajectory.h.
References sim::TrajectoryAllocator.
{
     TrajectoryAllocator.FreeSingle((Trajectory*) aTrajectory);
 }
void * sim::Trajectory::operator new (size_t s) inline
Create a new trajectory.
Parameters
s The size of the object.
Definition at line 222 of file Trajectory.h.
References sim::TrajectoryAllocator.
{
     void* aTrajectory;
     aTrajectory = (void*) TrajectoryAllocator.MallocSingle();
     return aTrajectory;
 }
void sim::Trajectory::setGenStatus (int genStatus)
Set the generator status of the particle.
Parameters
genStatus The particle's generator status.
Definition at line 110 of file Trajectory.cxx.
References genStatus_.
Referenced by sim::UserTrackingAction::PreUserTrackingAction().
{
     genStatus_ = theGenStatus;
 }
Member Data Documentation
G4ThreeVector sim::Trajectory::endPoint_ private
The particle's end point.
Definition at line 214 of file Trajectory.h.
Referenced by getEndPoint().
G4double sim::Trajectory::energy_ private
The particle's energy.
Definition at line 184 of file Trajectory.h.
Referenced by getEnergy(), and Trajectory().
G4int sim::Trajectory::genStatus_ private
The particle's generator status.
Definition at line 199 of file Trajectory.h.
Referenced by getGenStatus(), and setGenStatus().
G4float sim::Trajectory::globalTime_ private
The particle's global time.
Definition at line 194 of file Trajectory.h.
Referenced by getGlobalTime(), and Trajectory().
G4ThreeVector sim::Trajectory::initialMomentum_ private
The particle's initial momentum.
Definition at line 204 of file Trajectory.h.
Referenced by GetInitialMomentum(), and Trajectory().
G4double sim::Trajectory::mass_ private
The particle's mass.
Definition at line 189 of file Trajectory.h.
Referenced by getMass(), and Trajectory().
G4int sim::Trajectory::parentID_ private
The parent track ID.
Definition at line 179 of file Trajectory.h.
Referenced by GetParentID(), and Trajectory().
G4ParticleDefinition* sim::Trajectory::particleDef_ private
The particle definition.
Definition at line 169 of file Trajectory.h.
Referenced by GetCharge(), GetParticleName(), GetPDGEncoding(), and Trajectory().
G4int sim::Trajectory::trackID_ private
The track ID.
Definition at line 174 of file Trajectory.h.
Referenced by GetTrackID(), and Trajectory().
TrajectoryPointContainer* sim::Trajectory::trajPoints_ private
The list of trajectory points.
Definition at line 164 of file Trajectory.h.
Referenced by AppendStep(), GetPoint(), GetPointEntries(), MergeTrajectory(), Trajectory(), and ~Trajectory().
G4ThreeVector sim::Trajectory::vertexPosition_ private
The particle's vertex position.
Definition at line 209 of file Trajectory.h.
Referenced by getVertexPosition(), and Trajectory().
The documentation for this class was generated from the following files:
SimApplication/include/SimApplication/Trajectory.h
SimApplication/src/Trajectory.cxx