LDMX Software: sim::G4CalorimeterHit Class Reference
sim::G4CalorimeterHit Class Reference
Calorimeter hit which is used to create output SimCalorimeterHit objects.
#include <G4CalorimeterHit.h>
Public Member Functions
G4CalorimeterHit ()
virtual ~G4CalorimeterHit ()
void Draw ()
void Print ()
std::ostream & print (std::ostream &os)
void * operator new (size_t s)
void operator delete (void *aHit)
G4int getTrackID ()
void setTrackID (int trackID)
int getID ()
void setID (int id)
float getEdep ()
void setEdep (float edep)
const G4ThreeVector & getPosition ()
void setPosition (const float x, const float y, const float z)
float getTime ()
void setTime (float time)
int getPdgCode ()
void setPdgCode (int pdgCode)
Private Attributes
int trackID_ {-1}
int id_ {0}
double edep_ {0}
G4ThreeVector position_
float time_ {0}
int pdgCode_ {0}
Detailed Description
Calorimeter hit which is used to create output SimCalorimeterHit objects.
One of these is created for every step in a CalorimeterSD. These hits are combined later at the end of the event by the RootPersistencyManager from matching their detector IDs.
Definition at line 31 of file G4CalorimeterHit.h.
Constructor & Destructor Documentation
sim::G4CalorimeterHit::G4CalorimeterHit () inline
Class constructor.
Definition at line 38 of file G4CalorimeterHit.h.
 {;}
virtual sim::G4CalorimeterHit::~G4CalorimeterHit () inline virtual
Class destructor.
Definition at line 43 of file G4CalorimeterHit.h.
 {;}
Member Function Documentation
void sim::G4CalorimeterHit::Draw ()
Draw the hit in the Geant4 runtime.
Definition at line 13 of file G4CalorimeterHit.cxx.
References position_.
{
     G4VVisManager* visManager = G4VVisManager::GetConcreteInstance();
     if(visManager) {
         G4Point3D p3D = G4Point3D(position_);
         G4Circle chit(p3D);
         chit.SetScreenDiameter(3.0);
         chit.SetFillStyle(G4Circle::filled);
         G4Colour col(1.0, 0.0, 1.0);
         chit.SetVisAttributes(G4VisAttributes(col));
         visManager->Draw(chit);
     }
 }
float sim::G4CalorimeterHit::getEdep () inline
Get the energy deposition of the hit.
Returns
The energy deposition of the hit.
Definition at line 110 of file G4CalorimeterHit.h.
References edep_.
Referenced by sim::RootPersistencyManager::writeCalorimeterHitsCollection(), and sim::EcalHitIO::writeHitsCollection().
{
             return edep_;
         }
int sim::G4CalorimeterHit::getID () inline
Get the detector ID of the hit.
Returns
The detector ID of the hit.
Definition at line 94 of file G4CalorimeterHit.h.
References id_.
Referenced by sim::RootPersistencyManager::writeCalorimeterHitsCollection(), and sim::EcalHitIO::writeHitsCollection().
                     {
             return id_;
         }
int sim::G4CalorimeterHit::getPdgCode () inline
Get the PDG code of the track that made this hit.
Returns
The PDG code of the track that made the hit.
Definition at line 160 of file G4CalorimeterHit.h.
References pdgCode_.
Referenced by sim::RootPersistencyManager::writeCalorimeterHitsCollection(), and sim::EcalHitIO::writeHitsCollection().
{
             return pdgCode_;
         }
const G4ThreeVector& sim::G4CalorimeterHit::getPosition () inline
Get the XYZ hit position [mm].
Returns
The hit position.
Definition at line 126 of file G4CalorimeterHit.h.
References position_.
Referenced by sim::RootPersistencyManager::writeCalorimeterHitsCollection(), and sim::EcalHitIO::writeHitsCollection().
{
             return position_;
         }
float sim::G4CalorimeterHit::getTime () inline
Get the global time of the hit [ns].
Returns
The global hit time.
Definition at line 144 of file G4CalorimeterHit.h.
References time_.
Referenced by sim::RootPersistencyManager::writeCalorimeterHitsCollection(), and sim::EcalHitIO::writeHitsCollection().
{
             return time_;
         }
G4int sim::G4CalorimeterHit::getTrackID () inline
Get the track ID of the hit.
Returns
The track ID of the hit.
Definition at line 78 of file G4CalorimeterHit.h.
References trackID_.
Referenced by sim::RootPersistencyManager::writeCalorimeterHitsCollection(), and sim::EcalHitIO::writeHitsCollection().
{
             return trackID_;
         }
void sim::G4CalorimeterHit::operator delete (void * aHit) inline
Delete a hit object.
Parameters
aHit The hit to delete.
Implementation of custom delete operator.
Definition at line 228 of file G4CalorimeterHit.h.
References sim::G4CalorimeterHitAllocator.
{
     G4CalorimeterHitAllocator.FreeSingle((G4CalorimeterHit*) aHit);
 }
void * sim::G4CalorimeterHit::operator new (size_t s) inline
Create a new hit object.
Parameters
s The size of the hit object.
Implementation of custom new operator.
Definition at line 219 of file G4CalorimeterHit.h.
References sim::G4CalorimeterHitAllocator.
{
     void* aHit;
     aHit = (void*) G4CalorimeterHitAllocator.MallocSingle();
     return aHit;
 }
void sim::G4CalorimeterHit::Print ()
Print information about the hit.
Definition at line 30 of file G4CalorimeterHit.cxx.
References print().
Referenced by sim::EcalSD::ProcessHits(), and sim::CalorimeterSD::ProcessHits().
{
     print(std::cout);
 }
std::ostream & sim::G4CalorimeterHit::print (std::ostream & os)
Print hit information to an output stream.
Parameters
os The output stream.
Returns
The same output stream.
Definition at line 34 of file G4CalorimeterHit.cxx.
References edep_, position_, and time_.
Referenced by Print().
{
     os << "G4CalorimeterHit { "
             << "edep: " << this->edep_ << ", "
             << "position: " << position_ << ", "
             << "time: " << this->time_
             << " }"
             << std::endl;
     return os;
 }
void sim::G4CalorimeterHit::setEdep (float edep) inline
Set the energy deposition.
Parameters
edep The energy deposition.
Definition at line 118 of file G4CalorimeterHit.h.
References edep_.
Referenced by sim::EcalSD::ProcessHits(), and sim::CalorimeterSD::ProcessHits().
{
             this->edep_ = edep;
         }
void sim::G4CalorimeterHit::setID (int id) inline
Set the detector ID.
Parameters
id The detector ID.
Definition at line 102 of file G4CalorimeterHit.h.
References id_.
Referenced by sim::EcalSD::ProcessHits(), and sim::CalorimeterSD::ProcessHits().
{
             this->id_ = id;
         }
void sim::G4CalorimeterHit::setPdgCode (int pdgCode) inline
Set the PDG code from the track that made the hit.
Parameters
pdgCode The PDG code.
Definition at line 168 of file G4CalorimeterHit.h.
References pdgCode_.
Referenced by sim::EcalSD::ProcessHits().
{
             pdgCode_ = pdgCode;
         }
void sim::G4CalorimeterHit::setPosition (const float x, const float y, const float z) inline
Set the hit position [mm].
Parameters
x The X position.
y The Y position.
z The Z position.
Definition at line 136 of file G4CalorimeterHit.h.
References position_.
Referenced by sim::EcalSD::ProcessHits(), and sim::CalorimeterSD::ProcessHits().
{
             position_.set(x, y, z);
         }
void sim::G4CalorimeterHit::setTime (float time) inline
Set the global hit time [ns].
Parameters
time The global hit time.
Definition at line 152 of file G4CalorimeterHit.h.
References time_.
Referenced by sim::EcalSD::ProcessHits(), and sim::CalorimeterSD::ProcessHits().
{
             this->time_ = time;
         }
void sim::G4CalorimeterHit::setTrackID (int trackID) inline
Set the track ID.
Parameters
trackID The track ID.
Definition at line 86 of file G4CalorimeterHit.h.
References trackID_.
Referenced by sim::EcalSD::ProcessHits(), and sim::CalorimeterSD::ProcessHits().
{
             this->trackID_ = trackID;
         }
Member Data Documentation
double sim::G4CalorimeterHit::edep_ {0} private
The energy deposition.
Definition at line 187 of file G4CalorimeterHit.h.
Referenced by getEdep(), print(), and setEdep().
int sim::G4CalorimeterHit::id_ {0} private
The detector ID.
Definition at line 182 of file G4CalorimeterHit.h.
Referenced by getID(), and setID().
int sim::G4CalorimeterHit::pdgCode_ {0} private
The PDG code.
Definition at line 202 of file G4CalorimeterHit.h.
Referenced by getPdgCode(), and setPdgCode().
G4ThreeVector sim::G4CalorimeterHit::position_ private
The hit position.
Definition at line 192 of file G4CalorimeterHit.h.
Referenced by Draw(), getPosition(), print(), and setPosition().
float sim::G4CalorimeterHit::time_ {0} private
The global time.
Definition at line 197 of file G4CalorimeterHit.h.
Referenced by getTime(), print(), and setTime().
int sim::G4CalorimeterHit::trackID_ {-1} private
The track ID.
Definition at line 177 of file G4CalorimeterHit.h.
Referenced by getTrackID(), and setTrackID().
The documentation for this class was generated from the following files:
SimApplication/include/SimApplication/G4CalorimeterHit.h
SimApplication/src/G4CalorimeterHit.cxx