LDMX Software: sim::G4TrackerHit Class Reference
sim::G4TrackerHit Class Reference
Track hit which is used to create output SimTrackerHit collection.
#include <G4TrackerHit.h>
Public Member Functions
G4TrackerHit ()
virtual ~G4TrackerHit ()
void Draw ()
void Print ()
std::ostream & print (std::ostream &os)
void * operator new (size_t s)
void operator delete (void *aHit)
void setTrackID (int trackID)
int getTrackID ()
int getID ()
void setID (int id)
int getLayerID ()
void setLayerID (int layerID)
float getEdep ()
void setEdep (float edep)
float getTime ()
void setTime (float time)
const G4ThreeVector & getMomentum ()
void setMomentum (float px, float py, float pz)
const G4ThreeVector & getPosition ()
void setPosition (float x, float y, float z)
float getPathLength ()
void setPathLength (float pathLength)
Private Attributes
G4int trackID_ {0}
int id_ {0}
int layerID_ {0}
float edep_ {0}
float time_ {0}
G4ThreeVector momentum_
G4ThreeVector position_
float pathLength_ {0}
Detailed Description
Track hit which is used to create output SimTrackerHit collection.
Note
One of these is created for every step in a TrackerSD. These are basically copied verbatim into SimTrackerHit objects by the RootPersistencyManager.
Definition at line 36 of file G4TrackerHit.h.
Constructor & Destructor Documentation
sim::G4TrackerHit::G4TrackerHit () inline
Class constructor.
Definition at line 43 of file G4TrackerHit.h.
 {;}
virtual sim::G4TrackerHit::~G4TrackerHit () inline virtual
Class destructor.
Definition at line 48 of file G4TrackerHit.h.
 {;}
Member Function Documentation
void sim::G4TrackerHit::Draw ()
Draw the hit in the Geant4 runtime.
Definition at line 13 of file G4TrackerHit.cxx.
References position_.
{
     G4VVisManager* visManager = G4VVisManager::GetConcreteInstance();
     if(visManager) {
         G4Point3D p3D = G4Point3D(this->position_);
         G4Circle chit(p3D);
         chit.SetScreenDiameter(3.0);
         chit.SetFillStyle(G4Circle::filled);
         G4Colour col(1.0, 0.0, 1.0);
         chit.SetVisAttributes(G4VisAttributes(col));
         visManager->Draw(chit);
     }
 }
float sim::G4TrackerHit::getEdep () inline
Get the energy deposition.
Returns
The energy deposition.
Definition at line 131 of file G4TrackerHit.h.
References edep_.
Referenced by sim::RootPersistencyManager::writeTrackerHitsCollection().
{
             return edep_;
         }
int sim::G4TrackerHit::getID () inline
Get the detector ID.
Returns
The detector ID.
Definition at line 99 of file G4TrackerHit.h.
References id_.
Referenced by sim::RootPersistencyManager::writeTrackerHitsCollection().
                     {
             return id_;
         }
int sim::G4TrackerHit::getLayerID () inline
Get the layer ID.
Returns
The layer ID.
Definition at line 115 of file G4TrackerHit.h.
References layerID_.
Referenced by sim::RootPersistencyManager::writeTrackerHitsCollection().
{
             return layerID_;
         }
const G4ThreeVector& sim::G4TrackerHit::getMomentum () inline
Get the XYZ momentum.
Returns
The XYZ momentum.
Definition at line 163 of file G4TrackerHit.h.
References momentum_.
Referenced by sim::RootPersistencyManager::writeTrackerHitsCollection().
{
             return momentum_;
         }
float sim::G4TrackerHit::getPathLength () inline
Get the path length from the pre and post step points [mm].
Returns
The path length.
Definition at line 203 of file G4TrackerHit.h.
References pathLength_.
Referenced by sim::RootPersistencyManager::writeTrackerHitsCollection().
{
             return pathLength_;
         }
const G4ThreeVector& sim::G4TrackerHit::getPosition () inline
Get the XYZ hit position [mm].
Returns
The hit position.
Definition at line 183 of file G4TrackerHit.h.
References position_.
Referenced by sim::RootPersistencyManager::writeTrackerHitsCollection().
{
             return position_;
         }
float sim::G4TrackerHit::getTime () inline
Get the global time.
Returns
The global time.
Definition at line 147 of file G4TrackerHit.h.
References time_.
{
             return time_;
         }
int sim::G4TrackerHit::getTrackID () inline
Get the track ID.
Returns
The track ID.
Definition at line 91 of file G4TrackerHit.h.
References trackID_.
Referenced by sim::RootPersistencyManager::writeTrackerHitsCollection().
{
             return this->trackID_;
         }
void sim::G4TrackerHit::operator delete (void * aHit) inline
Delete a hit object.
Parameters
aHit The hit to delete.
Implementation of custom delete operator.
Definition at line 280 of file G4TrackerHit.h.
References sim::G4TrackerHitAllocator.
{
     G4TrackerHitAllocator.FreeSingle((G4TrackerHit*) aHit);
 }
void * sim::G4TrackerHit::operator new (size_t s) inline
Create a new hit object.
Parameters
s The size of the hit object.
Implementation of custom new operator.
Definition at line 271 of file G4TrackerHit.h.
References sim::G4TrackerHitAllocator.
{
     void* aHit;
     aHit = (void*) G4TrackerHitAllocator.MallocSingle();
     return aHit;
 }
void sim::G4TrackerHit::Print ()
Print out hit information.
Definition at line 31 of file G4TrackerHit.cxx.
References print().
Referenced by sim::TrackerSD::ProcessHits().
{
     print(std::cout);
 }
std::ostream & sim::G4TrackerHit::print (std::ostream & os)
Print hit information to an output stream.
Parameters
os The output stream.
Returns
The same output stream.
Definition at line 35 of file G4TrackerHit.cxx.
References edep_, layerID_, momentum_, pathLength_, position_, and time_.
Referenced by Print().
{
     os << "G4TrackerHit { "
             "edep: " << this->edep_ << ", "
             "position: (" << this->position_[0] << ", "
             << this->position_[1] << ", "
             << this->position_[2] << "), "
             << "layerID: " << this->layerID_ << ", "
             << "momentum: (" << this->momentum_[0] << ", "
             << this->momentum_[1] << ", "
             << this->momentum_[2] << "), "
             << "pathLength: " << this->pathLength_ << ", "
             << "time: " << this->time_
             << " }"
             << std::endl;
     return os;
 }
void sim::G4TrackerHit::setEdep (float edep) inline
Set the energy deposition.
Parameters
edep The energy deposition.
Definition at line 139 of file G4TrackerHit.h.
References edep_.
Referenced by sim::TrackerSD::ProcessHits().
{
             this->edep_ = edep;
         }
void sim::G4TrackerHit::setID (int id) inline
Set the detector ID.
Parameters
id The detector ID.
Definition at line 107 of file G4TrackerHit.h.
References id_.
Referenced by sim::TrackerSD::ProcessHits().
{
             this->id_ = id;
         }
void sim::G4TrackerHit::setLayerID (int layerID) inline
Set the layer ID.
Parameters
layerID The layer ID.
Definition at line 123 of file G4TrackerHit.h.
References layerID_.
Referenced by sim::TrackerSD::ProcessHits().
{
             this->layerID_ = layerID;
         }
void sim::G4TrackerHit::setMomentum (float px, float py, float pz) inline
Set the momentum.
Parameters
px The X momentum.
py The Y momentum.
pz The Z momentum.
Definition at line 173 of file G4TrackerHit.h.
References momentum_.
Referenced by sim::TrackerSD::ProcessHits().
{
             momentum_.setX(px);
             momentum_.setY(py);
             momentum_.setZ(pz);
         }
void sim::G4TrackerHit::setPathLength (float pathLength) inline
Set the path length [mm]. The path length.
Definition at line 211 of file G4TrackerHit.h.
References pathLength_.
Referenced by sim::TrackerSD::ProcessHits().
{
             this->pathLength_ = pathLength;
         }
void sim::G4TrackerHit::setPosition (float x, float y, float z) inline
Set the hit position [mm].
Parameters
x The X position.
y The Y position. 2param z The Z position.
Definition at line 193 of file G4TrackerHit.h.
References position_.
Referenced by sim::TrackerSD::ProcessHits().
{
             position_.setX(x);
             position_.setY(y);
             position_.setZ(z);
         }
void sim::G4TrackerHit::setTime (float time) inline
Set the global time.
Parameters
time The global time.
Definition at line 155 of file G4TrackerHit.h.
References time_.
Referenced by sim::TrackerSD::ProcessHits().
{
             this->time_ = time;
         }
void sim::G4TrackerHit::setTrackID (int trackID) inline
Set the track ID.
Parameters
trackID The track ID.
Definition at line 83 of file G4TrackerHit.h.
References trackID_.
Referenced by sim::TrackerSD::ProcessHits().
{
             this->trackID_ = trackID;
         }
Member Data Documentation
float sim::G4TrackerHit::edep_ {0} private
The energy deposition.
Definition at line 235 of file G4TrackerHit.h.
Referenced by getEdep(), print(), and setEdep().
int sim::G4TrackerHit::id_ {0} private
The detector ID.
Definition at line 225 of file G4TrackerHit.h.
Referenced by getID(), and setID().
int sim::G4TrackerHit::layerID_ {0} private
The layer ID.
Definition at line 230 of file G4TrackerHit.h.
Referenced by getLayerID(), print(), and setLayerID().
G4ThreeVector sim::G4TrackerHit::momentum_ private
The XYZ momentum.
Definition at line 245 of file G4TrackerHit.h.
Referenced by getMomentum(), print(), and setMomentum().
float sim::G4TrackerHit::pathLength_ {0} private
The path length.
Definition at line 255 of file G4TrackerHit.h.
Referenced by getPathLength(), print(), and setPathLength().
G4ThreeVector sim::G4TrackerHit::position_ private
The XYZ position.
Definition at line 250 of file G4TrackerHit.h.
Referenced by Draw(), getPosition(), print(), and setPosition().
float sim::G4TrackerHit::time_ {0} private
The global time.
Definition at line 240 of file G4TrackerHit.h.
Referenced by getTime(), print(), and setTime().
G4int sim::G4TrackerHit::trackID_ {0} private
The track ID.
Definition at line 220 of file G4TrackerHit.h.
Referenced by getTrackID(), and setTrackID().
The documentation for this class was generated from the following files:
SimApplication/include/SimApplication/G4TrackerHit.h
SimApplication/src/G4TrackerHit.cxx